// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/proto/v1/artifact_service.proto

package protov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ArtifactName  string                 `protobuf:"bytes,3,opt,name=artifact_name,json=artifactName,proto3" json:"artifact_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_api_proto_v1_artifact_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_artifact_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_artifact_service_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UploadRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UploadRequest) GetArtifactName() string {
	if x != nil {
		return x.ArtifactName
	}
	return ""
}

func (x *UploadRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadUrl     string                 `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`          // Pre-signed S3/MinIO URL
	ArtifactId    string                 `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`       // Unique artifact identifier
	ExpiresAtMs   int64                  `protobuf:"varint,3,opt,name=expires_at_ms,json=expiresAtMs,proto3" json:"expires_at_ms,omitempty"` // URL expiration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_api_proto_v1_artifact_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_artifact_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_artifact_service_proto_rawDescGZIP(), []int{1}
}

func (x *UploadResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *UploadResponse) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *UploadResponse) GetExpiresAtMs() int64 {
	if x != nil {
		return x.ExpiresAtMs
	}
	return 0
}

type ArtifactMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId     string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	TaskId         string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ContentType    string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes      int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ChecksumSha256 string                 `protobuf:"bytes,6,opt,name=checksum_sha256,json=checksumSha256,proto3" json:"checksum_sha256,omitempty"`
	Labels         map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g., {"type": "wheel", "python": "3.11"}
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ArtifactMetadata) Reset() {
	*x = ArtifactMetadata{}
	mi := &file_api_proto_v1_artifact_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactMetadata) ProtoMessage() {}

func (x *ArtifactMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_artifact_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactMetadata.ProtoReflect.Descriptor instead.
func (*ArtifactMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_artifact_service_proto_rawDescGZIP(), []int{2}
}

func (x *ArtifactMetadata) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ArtifactMetadata) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ArtifactMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArtifactMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ArtifactMetadata) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ArtifactMetadata) GetChecksumSha256() string {
	if x != nil {
		return x.ChecksumSha256
	}
	return ""
}

func (x *ArtifactMetadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recorded      bool                   `protobuf:"varint,1,opt,name=recorded,proto3" json:"recorded,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,2,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"` // Pre-signed download URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactResponse) Reset() {
	*x = ArtifactResponse{}
	mi := &file_api_proto_v1_artifact_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactResponse) ProtoMessage() {}

func (x *ArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_artifact_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactResponse.ProtoReflect.Descriptor instead.
func (*ArtifactResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_artifact_service_proto_rawDescGZIP(), []int{3}
}

func (x *ArtifactResponse) GetRecorded() bool {
	if x != nil {
		return x.Recorded
	}
	return false
}

func (x *ArtifactResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

var File_api_proto_v1_artifact_service_proto protoreflect.FileDescriptor

const file_api_proto_v1_artifact_service_proto_rawDesc = "" +
	"\n" +
	"#api/proto/v1/artifact_service.proto\x12\n" +
	"codegen.v1\"\xae\x01\n" +
	"\rUploadRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12#\n" +
	"\rartifact_name\x18\x03 \x01(\tR\fartifactName\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\"t\n" +
	"\x0eUploadResponse\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x01 \x01(\tR\tuploadUrl\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\x12\"\n" +
	"\rexpires_at_ms\x18\x03 \x01(\x03R\vexpiresAtMs\"\xc8\x02\n" +
	"\x10ArtifactMetadata\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x12'\n" +
	"\x0fchecksum_sha256\x18\x06 \x01(\tR\x0echecksumSha256\x12@\n" +
	"\x06labels\x18\a \x03(\v2(.codegen.v1.ArtifactMetadata.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\x10ArtifactResponse\x12\x1a\n" +
	"\brecorded\x18\x01 \x01(\bR\brecorded\x12!\n" +
	"\fdownload_url\x18\x02 \x01(\tR\vdownloadUrl2\xa6\x01\n" +
	"\x0fArtifactService\x12E\n" +
	"\fGetUploadURL\x12\x19.codegen.v1.UploadRequest\x1a\x1a.codegen.v1.UploadResponse\x12L\n" +
	"\x0eRecordArtifact\x12\x1c.codegen.v1.ArtifactMetadata\x1a\x1c.codegen.v1.ArtifactResponseB9Z7github.com/altairalabs/codegen-mcp/api/proto/v1;protov1b\x06proto3"

var (
	file_api_proto_v1_artifact_service_proto_rawDescOnce sync.Once
	file_api_proto_v1_artifact_service_proto_rawDescData []byte
)

func file_api_proto_v1_artifact_service_proto_rawDescGZIP() []byte {
	file_api_proto_v1_artifact_service_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_artifact_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_artifact_service_proto_rawDesc), len(file_api_proto_v1_artifact_service_proto_rawDesc)))
	})
	return file_api_proto_v1_artifact_service_proto_rawDescData
}

var file_api_proto_v1_artifact_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_v1_artifact_service_proto_goTypes = []any{
	(*UploadRequest)(nil),    // 0: codegen.v1.UploadRequest
	(*UploadResponse)(nil),   // 1: codegen.v1.UploadResponse
	(*ArtifactMetadata)(nil), // 2: codegen.v1.ArtifactMetadata
	(*ArtifactResponse)(nil), // 3: codegen.v1.ArtifactResponse
	nil,                      // 4: codegen.v1.ArtifactMetadata.LabelsEntry
}
var file_api_proto_v1_artifact_service_proto_depIdxs = []int32{
	4, // 0: codegen.v1.ArtifactMetadata.labels:type_name -> codegen.v1.ArtifactMetadata.LabelsEntry
	0, // 1: codegen.v1.ArtifactService.GetUploadURL:input_type -> codegen.v1.UploadRequest
	2, // 2: codegen.v1.ArtifactService.RecordArtifact:input_type -> codegen.v1.ArtifactMetadata
	1, // 3: codegen.v1.ArtifactService.GetUploadURL:output_type -> codegen.v1.UploadResponse
	3, // 4: codegen.v1.ArtifactService.RecordArtifact:output_type -> codegen.v1.ArtifactResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_v1_artifact_service_proto_init() }
func file_api_proto_v1_artifact_service_proto_init() {
	if File_api_proto_v1_artifact_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_artifact_service_proto_rawDesc), len(file_api_proto_v1_artifact_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_artifact_service_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_artifact_service_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_artifact_service_proto_msgTypes,
	}.Build()
	File_api_proto_v1_artifact_service_proto = out.File
	file_api_proto_v1_artifact_service_proto_goTypes = nil
	file_api_proto_v1_artifact_service_proto_depIdxs = nil
}
