// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/proto/v1/common.proto

package protov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionState represents the lifecycle state of a session
type SessionState int32

const (
	SessionState_SESSION_STATE_UNSPECIFIED   SessionState = 0
	SessionState_SESSION_STATE_INITIALIZING  SessionState = 1
	SessionState_SESSION_STATE_READY         SessionState = 2
	SessionState_SESSION_STATE_BUSY          SessionState = 3
	SessionState_SESSION_STATE_IDLE          SessionState = 4
	SessionState_SESSION_STATE_DRAINING      SessionState = 5 // Session being cleaned up
	SessionState_SESSION_STATE_CHECKPOINTING SessionState = 6 // State being saved
	SessionState_SESSION_STATE_FAILED        SessionState = 7
)

// Enum value maps for SessionState.
var (
	SessionState_name = map[int32]string{
		0: "SESSION_STATE_UNSPECIFIED",
		1: "SESSION_STATE_INITIALIZING",
		2: "SESSION_STATE_READY",
		3: "SESSION_STATE_BUSY",
		4: "SESSION_STATE_IDLE",
		5: "SESSION_STATE_DRAINING",
		6: "SESSION_STATE_CHECKPOINTING",
		7: "SESSION_STATE_FAILED",
	}
	SessionState_value = map[string]int32{
		"SESSION_STATE_UNSPECIFIED":   0,
		"SESSION_STATE_INITIALIZING":  1,
		"SESSION_STATE_READY":         2,
		"SESSION_STATE_BUSY":          3,
		"SESSION_STATE_IDLE":          4,
		"SESSION_STATE_DRAINING":      5,
		"SESSION_STATE_CHECKPOINTING": 6,
		"SESSION_STATE_FAILED":        7,
	}
)

func (x SessionState) Enum() *SessionState {
	p := new(SessionState)
	*p = x
	return p
}

func (x SessionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_common_proto_enumTypes[0].Descriptor()
}

func (SessionState) Type() protoreflect.EnumType {
	return &file_api_proto_v1_common_proto_enumTypes[0]
}

func (x SessionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionState.Descriptor instead.
func (SessionState) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_common_proto_rawDescGZIP(), []int{0}
}

// ResourceUsage tracks resource consumption
type ResourceUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryBytes   int64                  `protobuf:"varint,1,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	CpuMillicores int64                  `protobuf:"varint,2,opt,name=cpu_millicores,json=cpuMillicores,proto3" json:"cpu_millicores,omitempty"`
	DiskBytes     int64                  `protobuf:"varint,3,opt,name=disk_bytes,json=diskBytes,proto3" json:"disk_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceUsage) Reset() {
	*x = ResourceUsage{}
	mi := &file_api_proto_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsage) ProtoMessage() {}

func (x *ResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsage.ProtoReflect.Descriptor instead.
func (*ResourceUsage) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceUsage) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ResourceUsage) GetCpuMillicores() int64 {
	if x != nil {
		return x.CpuMillicores
	}
	return 0
}

func (x *ResourceUsage) GetDiskBytes() int64 {
	if x != nil {
		return x.DiskBytes
	}
	return 0
}

// ResourceLimits defines resource constraints
type ResourceLimits struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MaxMemoryBytes      int64                  `protobuf:"varint,1,opt,name=max_memory_bytes,json=maxMemoryBytes,proto3" json:"max_memory_bytes,omitempty"`
	MaxCpuMillicores    int64                  `protobuf:"varint,2,opt,name=max_cpu_millicores,json=maxCpuMillicores,proto3" json:"max_cpu_millicores,omitempty"`
	MaxDiskBytes        int64                  `protobuf:"varint,3,opt,name=max_disk_bytes,json=maxDiskBytes,proto3" json:"max_disk_bytes,omitempty"`
	MaxConcurrentTasks  int32                  `protobuf:"varint,4,opt,name=max_concurrent_tasks,json=maxConcurrentTasks,proto3" json:"max_concurrent_tasks,omitempty"`      // Max tasks across all sessions
	MaxMemoryPerSession int64                  `protobuf:"varint,5,opt,name=max_memory_per_session,json=maxMemoryPerSession,proto3" json:"max_memory_per_session,omitempty"` // Memory limit per session
	MaxDiskPerSession   int64                  `protobuf:"varint,6,opt,name=max_disk_per_session,json=maxDiskPerSession,proto3" json:"max_disk_per_session,omitempty"`       // Disk limit per session
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_api_proto_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceLimits) GetMaxMemoryBytes() int64 {
	if x != nil {
		return x.MaxMemoryBytes
	}
	return 0
}

func (x *ResourceLimits) GetMaxCpuMillicores() int64 {
	if x != nil {
		return x.MaxCpuMillicores
	}
	return 0
}

func (x *ResourceLimits) GetMaxDiskBytes() int64 {
	if x != nil {
		return x.MaxDiskBytes
	}
	return 0
}

func (x *ResourceLimits) GetMaxConcurrentTasks() int32 {
	if x != nil {
		return x.MaxConcurrentTasks
	}
	return 0
}

func (x *ResourceLimits) GetMaxMemoryPerSession() int64 {
	if x != nil {
		return x.MaxMemoryPerSession
	}
	return 0
}

func (x *ResourceLimits) GetMaxDiskPerSession() int64 {
	if x != nil {
		return x.MaxDiskPerSession
	}
	return 0
}

// SessionInfo contains details about an active session
type SessionInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`       // Unique session identifier
	WorkspaceId    string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"` // Associated workspace
	CreatedAtMs    int64                  `protobuf:"varint,3,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	LastActivityMs int64                  `protobuf:"varint,4,opt,name=last_activity_ms,json=lastActivityMs,proto3" json:"last_activity_ms,omitempty"`
	State          SessionState           `protobuf:"varint,5,opt,name=state,proto3,enum=codegen.v1.SessionState" json:"state,omitempty"`
	Usage          *ResourceUsage         `protobuf:"bytes,6,opt,name=usage,proto3" json:"usage,omitempty"`                                 // Per-session resource usage
	ActiveTasks    int32                  `protobuf:"varint,7,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"` // Tasks running in this session
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_api_proto_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *SessionInfo) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

func (x *SessionInfo) GetLastActivityMs() int64 {
	if x != nil {
		return x.LastActivityMs
	}
	return 0
}

func (x *SessionInfo) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *SessionInfo) GetUsage() *ResourceUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *SessionInfo) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

var File_api_proto_v1_common_proto protoreflect.FileDescriptor

const file_api_proto_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/v1/common.proto\x12\n" +
	"codegen.v1\"x\n" +
	"\rResourceUsage\x12!\n" +
	"\fmemory_bytes\x18\x01 \x01(\x03R\vmemoryBytes\x12%\n" +
	"\x0ecpu_millicores\x18\x02 \x01(\x03R\rcpuMillicores\x12\x1d\n" +
	"\n" +
	"disk_bytes\x18\x03 \x01(\x03R\tdiskBytes\"\xa6\x02\n" +
	"\x0eResourceLimits\x12(\n" +
	"\x10max_memory_bytes\x18\x01 \x01(\x03R\x0emaxMemoryBytes\x12,\n" +
	"\x12max_cpu_millicores\x18\x02 \x01(\x03R\x10maxCpuMillicores\x12$\n" +
	"\x0emax_disk_bytes\x18\x03 \x01(\x03R\fmaxDiskBytes\x120\n" +
	"\x14max_concurrent_tasks\x18\x04 \x01(\x05R\x12maxConcurrentTasks\x123\n" +
	"\x16max_memory_per_session\x18\x05 \x01(\x03R\x13maxMemoryPerSession\x12/\n" +
	"\x14max_disk_per_session\x18\x06 \x01(\x03R\x11maxDiskPerSession\"\xa1\x02\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\"\n" +
	"\rcreated_at_ms\x18\x03 \x01(\x03R\vcreatedAtMs\x12(\n" +
	"\x10last_activity_ms\x18\x04 \x01(\x03R\x0elastActivityMs\x12.\n" +
	"\x05state\x18\x05 \x01(\x0e2\x18.codegen.v1.SessionStateR\x05state\x12/\n" +
	"\x05usage\x18\x06 \x01(\v2\x19.codegen.v1.ResourceUsageR\x05usage\x12!\n" +
	"\factive_tasks\x18\a \x01(\x05R\vactiveTasks*\xed\x01\n" +
	"\fSessionState\x12\x1d\n" +
	"\x19SESSION_STATE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSESSION_STATE_INITIALIZING\x10\x01\x12\x17\n" +
	"\x13SESSION_STATE_READY\x10\x02\x12\x16\n" +
	"\x12SESSION_STATE_BUSY\x10\x03\x12\x16\n" +
	"\x12SESSION_STATE_IDLE\x10\x04\x12\x1a\n" +
	"\x16SESSION_STATE_DRAINING\x10\x05\x12\x1f\n" +
	"\x1bSESSION_STATE_CHECKPOINTING\x10\x06\x12\x18\n" +
	"\x14SESSION_STATE_FAILED\x10\aB9Z7github.com/altairalabs/codegen-mcp/api/proto/v1;protov1b\x06proto3"

var (
	file_api_proto_v1_common_proto_rawDescOnce sync.Once
	file_api_proto_v1_common_proto_rawDescData []byte
)

func file_api_proto_v1_common_proto_rawDescGZIP() []byte {
	file_api_proto_v1_common_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_common_proto_rawDesc), len(file_api_proto_v1_common_proto_rawDesc)))
	})
	return file_api_proto_v1_common_proto_rawDescData
}

var file_api_proto_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_v1_common_proto_goTypes = []any{
	(SessionState)(0),      // 0: codegen.v1.SessionState
	(*ResourceUsage)(nil),  // 1: codegen.v1.ResourceUsage
	(*ResourceLimits)(nil), // 2: codegen.v1.ResourceLimits
	(*SessionInfo)(nil),    // 3: codegen.v1.SessionInfo
}
var file_api_proto_v1_common_proto_depIdxs = []int32{
	0, // 0: codegen.v1.SessionInfo.state:type_name -> codegen.v1.SessionState
	1, // 1: codegen.v1.SessionInfo.usage:type_name -> codegen.v1.ResourceUsage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_v1_common_proto_init() }
func file_api_proto_v1_common_proto_init() {
	if File_api_proto_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_common_proto_rawDesc), len(file_api_proto_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_v1_common_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_common_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_common_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_common_proto_msgTypes,
	}.Build()
	File_api_proto_v1_common_proto = out.File
	file_api_proto_v1_common_proto_goTypes = nil
	file_api_proto_v1_common_proto_depIdxs = nil
}
