// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: api/proto/v1/session_management.proto

package protov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SessionManagement_CreateSession_FullMethodName     = "/codegen.v1.SessionManagement/CreateSession"
	SessionManagement_DestroySession_FullMethodName    = "/codegen.v1.SessionManagement/DestroySession"
	SessionManagement_CheckpointSession_FullMethodName = "/codegen.v1.SessionManagement/CheckpointSession"
	SessionManagement_RestoreSession_FullMethodName    = "/codegen.v1.SessionManagement/RestoreSession"
	SessionManagement_GetSessionStatus_FullMethodName  = "/codegen.v1.SessionManagement/GetSessionStatus"
)

// SessionManagementClient is the client API for SessionManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SessionManagement handles session lifecycle and recovery
type SessionManagementClient interface {
	// Create a new session on a worker
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	// Destroy a session and cleanup resources
	DestroySession(ctx context.Context, in *DestroySessionRequest, opts ...grpc.CallOption) (*DestroySessionResponse, error)
	// Checkpoint session state for recovery
	CheckpointSession(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error)
	// Restore session from checkpoint
	RestoreSession(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
	// Get session status and metadata
	GetSessionStatus(ctx context.Context, in *SessionStatusRequest, opts ...grpc.CallOption) (*SessionStatusResponse, error)
}

type sessionManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionManagementClient(cc grpc.ClientConnInterface) SessionManagementClient {
	return &sessionManagementClient{cc}
}

func (c *sessionManagementClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, SessionManagement_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagementClient) DestroySession(ctx context.Context, in *DestroySessionRequest, opts ...grpc.CallOption) (*DestroySessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroySessionResponse)
	err := c.cc.Invoke(ctx, SessionManagement_DestroySession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagementClient) CheckpointSession(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointResponse)
	err := c.cc.Invoke(ctx, SessionManagement_CheckpointSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagementClient) RestoreSession(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreResponse)
	err := c.cc.Invoke(ctx, SessionManagement_RestoreSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagementClient) GetSessionStatus(ctx context.Context, in *SessionStatusRequest, opts ...grpc.CallOption) (*SessionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionStatusResponse)
	err := c.cc.Invoke(ctx, SessionManagement_GetSessionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionManagementServer is the server API for SessionManagement service.
// All implementations must embed UnimplementedSessionManagementServer
// for forward compatibility.
//
// SessionManagement handles session lifecycle and recovery
type SessionManagementServer interface {
	// Create a new session on a worker
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	// Destroy a session and cleanup resources
	DestroySession(context.Context, *DestroySessionRequest) (*DestroySessionResponse, error)
	// Checkpoint session state for recovery
	CheckpointSession(context.Context, *CheckpointRequest) (*CheckpointResponse, error)
	// Restore session from checkpoint
	RestoreSession(context.Context, *RestoreRequest) (*RestoreResponse, error)
	// Get session status and metadata
	GetSessionStatus(context.Context, *SessionStatusRequest) (*SessionStatusResponse, error)
	mustEmbedUnimplementedSessionManagementServer()
}

// UnimplementedSessionManagementServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionManagementServer struct{}

func (UnimplementedSessionManagementServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedSessionManagementServer) DestroySession(context.Context, *DestroySessionRequest) (*DestroySessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroySession not implemented")
}
func (UnimplementedSessionManagementServer) CheckpointSession(context.Context, *CheckpointRequest) (*CheckpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckpointSession not implemented")
}
func (UnimplementedSessionManagementServer) RestoreSession(context.Context, *RestoreRequest) (*RestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreSession not implemented")
}
func (UnimplementedSessionManagementServer) GetSessionStatus(context.Context, *SessionStatusRequest) (*SessionStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionStatus not implemented")
}
func (UnimplementedSessionManagementServer) mustEmbedUnimplementedSessionManagementServer() {}
func (UnimplementedSessionManagementServer) testEmbeddedByValue()                           {}

// UnsafeSessionManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionManagementServer will
// result in compilation errors.
type UnsafeSessionManagementServer interface {
	mustEmbedUnimplementedSessionManagementServer()
}

func RegisterSessionManagementServer(s grpc.ServiceRegistrar, srv SessionManagementServer) {
	// If the following call pancis, it indicates UnimplementedSessionManagementServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionManagement_ServiceDesc, srv)
}

func _SessionManagement_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagementServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManagement_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagementServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManagement_DestroySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroySessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagementServer).DestroySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManagement_DestroySession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagementServer).DestroySession(ctx, req.(*DestroySessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManagement_CheckpointSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagementServer).CheckpointSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManagement_CheckpointSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagementServer).CheckpointSession(ctx, req.(*CheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManagement_RestoreSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagementServer).RestoreSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManagement_RestoreSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagementServer).RestoreSession(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManagement_GetSessionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagementServer).GetSessionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManagement_GetSessionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagementServer).GetSessionStatus(ctx, req.(*SessionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionManagement_ServiceDesc is the grpc.ServiceDesc for SessionManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "codegen.v1.SessionManagement",
	HandlerType: (*SessionManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _SessionManagement_CreateSession_Handler,
		},
		{
			MethodName: "DestroySession",
			Handler:    _SessionManagement_DestroySession_Handler,
		},
		{
			MethodName: "CheckpointSession",
			Handler:    _SessionManagement_CheckpointSession_Handler,
		},
		{
			MethodName: "RestoreSession",
			Handler:    _SessionManagement_RestoreSession_Handler,
		},
		{
			MethodName: "GetSessionStatus",
			Handler:    _SessionManagement_GetSessionStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/session_management.proto",
}
