// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/proto/v1/session_management.proto

package protov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`          // Target worker (or empty for auto-assignment)
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"` // Workspace identifier
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // User/tenant identifier
	Config        *SessionConfig         `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_api_proto_v1_session_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_session_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_session_management_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *CreateSessionRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CreateSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateSessionRequest) GetConfig() *SessionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type SessionConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvVars       map[string]string      `protobuf:"bytes,1,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequiredTools []string               `protobuf:"bytes,2,rep,name=required_tools,json=requiredTools,proto3" json:"required_tools,omitempty"` // Tools this session needs
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`                                // e.g., "python"
	Limits        *ResourceLimits        `protobuf:"bytes,4,opt,name=limits,proto3" json:"limits,omitempty"`                                    // Per-session resource limits
	BaseImage     string                 `protobuf:"bytes,5,opt,name=base_image,json=baseImage,proto3" json:"base_image,omitempty"`             // Container image (optional override)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionConfig) Reset() {
	*x = SessionConfig{}
	mi := &file_api_proto_v1_session_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionConfig) ProtoMessage() {}

func (x *SessionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_session_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionConfig.ProtoReflect.Descriptor instead.
func (*SessionConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_session_management_proto_rawDescGZIP(), []int{1}
}

func (x *SessionConfig) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *SessionConfig) GetRequiredTools() []string {
	if x != nil {
		return x.RequiredTools
	}
	return nil
}

func (x *SessionConfig) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SessionConfig) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *SessionConfig) GetBaseImage() string {
	if x != nil {
		return x.BaseImage
	}
	return ""
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`             // Unique session identifier
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`                // Assigned worker
	WorkspacePath string                 `protobuf:"bytes,3,opt,name=workspace_path,json=workspacePath,proto3" json:"workspace_path,omitempty"` // Path to workspace on worker
	State         SessionState           `protobuf:"varint,4,opt,name=state,proto3,enum=codegen.v1.SessionState" json:"state,omitempty"`
	CreatedAtMs   int64                  `protobuf:"varint,5,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_api_proto_v1_session_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_session_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_session_management_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSessionResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *CreateSessionResponse) GetWorkspacePath() string {
	if x != nil {
		return x.WorkspacePath
	}
	return ""
}

func (x *CreateSessionResponse) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *CreateSessionResponse) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

type DestroySessionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Force          bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`                                         // Force destroy even if tasks running
	SaveCheckpoint bool                   `protobuf:"varint,3,opt,name=save_checkpoint,json=saveCheckpoint,proto3" json:"save_checkpoint,omitempty"` // Checkpoint before destroy
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DestroySessionRequest) Reset() {
	*x = DestroySessionRequest{}
	mi := &file_api_proto_v1_session_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySessionRequest) ProtoMessage() {}

func (x *DestroySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_session_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySessionRequest.ProtoReflect.Descriptor instead.
func (*DestroySessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_session_management_proto_rawDescGZIP(), []int{3}
}

func (x *DestroySessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DestroySessionRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *DestroySessionRequest) GetSaveCheckpoint() bool {
	if x != nil {
		return x.SaveCheckpoint
	}
	return false
}

type DestroySessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destroyed     bool                   `protobuf:"varint,1,opt,name=destroyed,proto3" json:"destroyed,omitempty"`
	CheckpointId  string                 `protobuf:"bytes,2,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"` // If save_checkpoint was true
	Artifacts     []string               `protobuf:"bytes,3,rep,name=artifacts,proto3" json:"artifacts,omitempty"`                           // Final artifacts from session
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySessionResponse) Reset() {
	*x = DestroySessionResponse{}
	mi := &file_api_proto_v1_session_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySessionResponse) ProtoMessage() {}

func (x *DestroySessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_session_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySessionResponse.ProtoReflect.Descriptor instead.
func (*DestroySessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_session_management_proto_rawDescGZIP(), []int{4}
}

func (x *DestroySessionResponse) GetDestroyed() bool {
	if x != nil {
		return x.Destroyed
	}
	return false
}

func (x *DestroySessionResponse) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *DestroySessionResponse) GetArtifacts() []string {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type CheckpointRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CheckpointName string                 `protobuf:"bytes,2,opt,name=checkpoint_name,json=checkpointName,proto3" json:"checkpoint_name,omitempty"` // Optional name for checkpoint
	Incremental    bool                   `protobuf:"varint,3,opt,name=incremental,proto3" json:"incremental,omitempty"`                            // Incremental vs. full checkpoint
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckpointRequest) Reset() {
	*x = CheckpointRequest{}
	mi := &file_api_proto_v1_session_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointRequest) ProtoMessage() {}

func (x *CheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_session_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointRequest.ProtoReflect.Descriptor instead.
func (*CheckpointRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_session_management_proto_rawDescGZIP(), []int{5}
}

func (x *CheckpointRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CheckpointRequest) GetCheckpointName() string {
	if x != nil {
		return x.CheckpointName
	}
	return ""
}

func (x *CheckpointRequest) GetIncremental() bool {
	if x != nil {
		return x.Incremental
	}
	return false
}

type CheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId  string                 `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"` // Unique checkpoint identifier
	SizeBytes     int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	StorageUrl    string                 `protobuf:"bytes,3,opt,name=storage_url,json=storageUrl,proto3" json:"storage_url,omitempty"` // Object storage URL
	Metadata      *CheckpointMetadata    `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointResponse) Reset() {
	*x = CheckpointResponse{}
	mi := &file_api_proto_v1_session_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointResponse) ProtoMessage() {}

func (x *CheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_session_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointResponse.ProtoReflect.Descriptor instead.
func (*CheckpointResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_session_management_proto_rawDescGZIP(), []int{6}
}

func (x *CheckpointResponse) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *CheckpointResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CheckpointResponse) GetStorageUrl() string {
	if x != nil {
		return x.StorageUrl
	}
	return ""
}

func (x *CheckpointResponse) GetMetadata() *CheckpointMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CheckpointMetadata struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WorkspaceId       string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	CreatedAtMs       int64                  `protobuf:"varint,3,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	EnvVars           map[string]string      `protobuf:"bytes,4,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	InstalledPackages []string               `protobuf:"bytes,5,rep,name=installed_packages,json=installedPackages,proto3" json:"installed_packages,omitempty"` // Python packages installed
	ModifiedFiles     []string               `protobuf:"bytes,6,rep,name=modified_files,json=modifiedFiles,proto3" json:"modified_files,omitempty"`             // Files changed from base
	ChecksumSha256    string                 `protobuf:"bytes,7,opt,name=checksum_sha256,json=checksumSha256,proto3" json:"checksum_sha256,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CheckpointMetadata) Reset() {
	*x = CheckpointMetadata{}
	mi := &file_api_proto_v1_session_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointMetadata) ProtoMessage() {}

func (x *CheckpointMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_session_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointMetadata.ProtoReflect.Descriptor instead.
func (*CheckpointMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_session_management_proto_rawDescGZIP(), []int{7}
}

func (x *CheckpointMetadata) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CheckpointMetadata) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CheckpointMetadata) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

func (x *CheckpointMetadata) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *CheckpointMetadata) GetInstalledPackages() []string {
	if x != nil {
		return x.InstalledPackages
	}
	return nil
}

func (x *CheckpointMetadata) GetModifiedFiles() []string {
	if x != nil {
		return x.ModifiedFiles
	}
	return nil
}

func (x *CheckpointMetadata) GetChecksumSha256() string {
	if x != nil {
		return x.ChecksumSha256
	}
	return ""
}

type RestoreRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId     string                 `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	WorkerId         string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`                            // Target worker (or empty for auto-assignment)
	CreateNewSession bool                   `protobuf:"varint,3,opt,name=create_new_session,json=createNewSession,proto3" json:"create_new_session,omitempty"` // Create new session or restore existing
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_api_proto_v1_session_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_session_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_session_management_proto_rawDescGZIP(), []int{8}
}

func (x *RestoreRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *RestoreRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RestoreRequest) GetCreateNewSession() bool {
	if x != nil {
		return x.CreateNewSession
	}
	return false
}

type RestoreResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionId          string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Restored or new session ID
	WorkerId           string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	State              SessionState           `protobuf:"varint,3,opt,name=state,proto3,enum=codegen.v1.SessionState" json:"state,omitempty"`
	CheckpointMetadata *CheckpointMetadata    `protobuf:"bytes,4,opt,name=checkpoint_metadata,json=checkpointMetadata,proto3" json:"checkpoint_metadata,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_api_proto_v1_session_management_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_session_management_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_session_management_proto_rawDescGZIP(), []int{9}
}

func (x *RestoreResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RestoreResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RestoreResponse) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *RestoreResponse) GetCheckpointMetadata() *CheckpointMetadata {
	if x != nil {
		return x.CheckpointMetadata
	}
	return nil
}

type SessionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStatusRequest) Reset() {
	*x = SessionStatusRequest{}
	mi := &file_api_proto_v1_session_management_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatusRequest) ProtoMessage() {}

func (x *SessionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_session_management_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatusRequest.ProtoReflect.Descriptor instead.
func (*SessionStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_session_management_proto_rawDescGZIP(), []int{10}
}

func (x *SessionStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionStatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WorkerId         string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	State            SessionState           `protobuf:"varint,3,opt,name=state,proto3,enum=codegen.v1.SessionState" json:"state,omitempty"`
	Info             *SessionInfo           `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	RecentTasks      []string               `protobuf:"bytes,5,rep,name=recent_tasks,json=recentTasks,proto3" json:"recent_tasks,omitempty"` // Recent task IDs
	LastCheckpointId string                 `protobuf:"bytes,6,opt,name=last_checkpoint_id,json=lastCheckpointId,proto3" json:"last_checkpoint_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SessionStatusResponse) Reset() {
	*x = SessionStatusResponse{}
	mi := &file_api_proto_v1_session_management_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatusResponse) ProtoMessage() {}

func (x *SessionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_session_management_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatusResponse.ProtoReflect.Descriptor instead.
func (*SessionStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_session_management_proto_rawDescGZIP(), []int{11}
}

func (x *SessionStatusResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionStatusResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *SessionStatusResponse) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *SessionStatusResponse) GetInfo() *SessionInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *SessionStatusResponse) GetRecentTasks() []string {
	if x != nil {
		return x.RecentTasks
	}
	return nil
}

func (x *SessionStatusResponse) GetLastCheckpointId() string {
	if x != nil {
		return x.LastCheckpointId
	}
	return ""
}

var File_api_proto_v1_session_management_proto protoreflect.FileDescriptor

const file_api_proto_v1_session_management_proto_rawDesc = "" +
	"\n" +
	"%api/proto/v1/session_management.proto\x12\n" +
	"codegen.v1\x1a\x19api/proto/v1/common.proto\"\xa2\x01\n" +
	"\x14CreateSessionRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x121\n" +
	"\x06config\x18\x04 \x01(\v2\x19.codegen.v1.SessionConfigR\x06config\"\xa4\x02\n" +
	"\rSessionConfig\x12A\n" +
	"\benv_vars\x18\x01 \x03(\v2&.codegen.v1.SessionConfig.EnvVarsEntryR\aenvVars\x12%\n" +
	"\x0erequired_tools\x18\x02 \x03(\tR\rrequiredTools\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x122\n" +
	"\x06limits\x18\x04 \x01(\v2\x1a.codegen.v1.ResourceLimitsR\x06limits\x12\x1d\n" +
	"\n" +
	"base_image\x18\x05 \x01(\tR\tbaseImage\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xce\x01\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12%\n" +
	"\x0eworkspace_path\x18\x03 \x01(\tR\rworkspacePath\x12.\n" +
	"\x05state\x18\x04 \x01(\x0e2\x18.codegen.v1.SessionStateR\x05state\x12\"\n" +
	"\rcreated_at_ms\x18\x05 \x01(\x03R\vcreatedAtMs\"u\n" +
	"\x15DestroySessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\x12'\n" +
	"\x0fsave_checkpoint\x18\x03 \x01(\bR\x0esaveCheckpoint\"y\n" +
	"\x16DestroySessionResponse\x12\x1c\n" +
	"\tdestroyed\x18\x01 \x01(\bR\tdestroyed\x12#\n" +
	"\rcheckpoint_id\x18\x02 \x01(\tR\fcheckpointId\x12\x1c\n" +
	"\tartifacts\x18\x03 \x03(\tR\tartifacts\"}\n" +
	"\x11CheckpointRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x0fcheckpoint_name\x18\x02 \x01(\tR\x0echeckpointName\x12 \n" +
	"\vincremental\x18\x03 \x01(\bR\vincremental\"\xb5\x01\n" +
	"\x12CheckpointResponse\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12\x1f\n" +
	"\vstorage_url\x18\x03 \x01(\tR\n" +
	"storageUrl\x12:\n" +
	"\bmetadata\x18\x04 \x01(\v2\x1e.codegen.v1.CheckpointMetadataR\bmetadata\"\xfd\x02\n" +
	"\x12CheckpointMetadata\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\"\n" +
	"\rcreated_at_ms\x18\x03 \x01(\x03R\vcreatedAtMs\x12F\n" +
	"\benv_vars\x18\x04 \x03(\v2+.codegen.v1.CheckpointMetadata.EnvVarsEntryR\aenvVars\x12-\n" +
	"\x12installed_packages\x18\x05 \x03(\tR\x11installedPackages\x12%\n" +
	"\x0emodified_files\x18\x06 \x03(\tR\rmodifiedFiles\x12'\n" +
	"\x0fchecksum_sha256\x18\a \x01(\tR\x0echecksumSha256\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x80\x01\n" +
	"\x0eRestoreRequest\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12,\n" +
	"\x12create_new_session\x18\x03 \x01(\bR\x10createNewSession\"\xce\x01\n" +
	"\x0fRestoreResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12.\n" +
	"\x05state\x18\x03 \x01(\x0e2\x18.codegen.v1.SessionStateR\x05state\x12O\n" +
	"\x13checkpoint_metadata\x18\x04 \x01(\v2\x1e.codegen.v1.CheckpointMetadataR\x12checkpointMetadata\"5\n" +
	"\x14SessionStatusRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x81\x02\n" +
	"\x15SessionStatusResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12.\n" +
	"\x05state\x18\x03 \x01(\x0e2\x18.codegen.v1.SessionStateR\x05state\x12+\n" +
	"\x04info\x18\x04 \x01(\v2\x17.codegen.v1.SessionInfoR\x04info\x12!\n" +
	"\frecent_tasks\x18\x05 \x03(\tR\vrecentTasks\x12,\n" +
	"\x12last_checkpoint_id\x18\x06 \x01(\tR\x10lastCheckpointId2\xba\x03\n" +
	"\x11SessionManagement\x12T\n" +
	"\rCreateSession\x12 .codegen.v1.CreateSessionRequest\x1a!.codegen.v1.CreateSessionResponse\x12W\n" +
	"\x0eDestroySession\x12!.codegen.v1.DestroySessionRequest\x1a\".codegen.v1.DestroySessionResponse\x12R\n" +
	"\x11CheckpointSession\x12\x1d.codegen.v1.CheckpointRequest\x1a\x1e.codegen.v1.CheckpointResponse\x12I\n" +
	"\x0eRestoreSession\x12\x1a.codegen.v1.RestoreRequest\x1a\x1b.codegen.v1.RestoreResponse\x12W\n" +
	"\x10GetSessionStatus\x12 .codegen.v1.SessionStatusRequest\x1a!.codegen.v1.SessionStatusResponseB9Z7github.com/altairalabs/codegen-mcp/api/proto/v1;protov1b\x06proto3"

var (
	file_api_proto_v1_session_management_proto_rawDescOnce sync.Once
	file_api_proto_v1_session_management_proto_rawDescData []byte
)

func file_api_proto_v1_session_management_proto_rawDescGZIP() []byte {
	file_api_proto_v1_session_management_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_session_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_session_management_proto_rawDesc), len(file_api_proto_v1_session_management_proto_rawDesc)))
	})
	return file_api_proto_v1_session_management_proto_rawDescData
}

var file_api_proto_v1_session_management_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_v1_session_management_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),   // 0: codegen.v1.CreateSessionRequest
	(*SessionConfig)(nil),          // 1: codegen.v1.SessionConfig
	(*CreateSessionResponse)(nil),  // 2: codegen.v1.CreateSessionResponse
	(*DestroySessionRequest)(nil),  // 3: codegen.v1.DestroySessionRequest
	(*DestroySessionResponse)(nil), // 4: codegen.v1.DestroySessionResponse
	(*CheckpointRequest)(nil),      // 5: codegen.v1.CheckpointRequest
	(*CheckpointResponse)(nil),     // 6: codegen.v1.CheckpointResponse
	(*CheckpointMetadata)(nil),     // 7: codegen.v1.CheckpointMetadata
	(*RestoreRequest)(nil),         // 8: codegen.v1.RestoreRequest
	(*RestoreResponse)(nil),        // 9: codegen.v1.RestoreResponse
	(*SessionStatusRequest)(nil),   // 10: codegen.v1.SessionStatusRequest
	(*SessionStatusResponse)(nil),  // 11: codegen.v1.SessionStatusResponse
	nil,                            // 12: codegen.v1.SessionConfig.EnvVarsEntry
	nil,                            // 13: codegen.v1.CheckpointMetadata.EnvVarsEntry
	(*ResourceLimits)(nil),         // 14: codegen.v1.ResourceLimits
	(SessionState)(0),              // 15: codegen.v1.SessionState
	(*SessionInfo)(nil),            // 16: codegen.v1.SessionInfo
}
var file_api_proto_v1_session_management_proto_depIdxs = []int32{
	1,  // 0: codegen.v1.CreateSessionRequest.config:type_name -> codegen.v1.SessionConfig
	12, // 1: codegen.v1.SessionConfig.env_vars:type_name -> codegen.v1.SessionConfig.EnvVarsEntry
	14, // 2: codegen.v1.SessionConfig.limits:type_name -> codegen.v1.ResourceLimits
	15, // 3: codegen.v1.CreateSessionResponse.state:type_name -> codegen.v1.SessionState
	7,  // 4: codegen.v1.CheckpointResponse.metadata:type_name -> codegen.v1.CheckpointMetadata
	13, // 5: codegen.v1.CheckpointMetadata.env_vars:type_name -> codegen.v1.CheckpointMetadata.EnvVarsEntry
	15, // 6: codegen.v1.RestoreResponse.state:type_name -> codegen.v1.SessionState
	7,  // 7: codegen.v1.RestoreResponse.checkpoint_metadata:type_name -> codegen.v1.CheckpointMetadata
	15, // 8: codegen.v1.SessionStatusResponse.state:type_name -> codegen.v1.SessionState
	16, // 9: codegen.v1.SessionStatusResponse.info:type_name -> codegen.v1.SessionInfo
	0,  // 10: codegen.v1.SessionManagement.CreateSession:input_type -> codegen.v1.CreateSessionRequest
	3,  // 11: codegen.v1.SessionManagement.DestroySession:input_type -> codegen.v1.DestroySessionRequest
	5,  // 12: codegen.v1.SessionManagement.CheckpointSession:input_type -> codegen.v1.CheckpointRequest
	8,  // 13: codegen.v1.SessionManagement.RestoreSession:input_type -> codegen.v1.RestoreRequest
	10, // 14: codegen.v1.SessionManagement.GetSessionStatus:input_type -> codegen.v1.SessionStatusRequest
	2,  // 15: codegen.v1.SessionManagement.CreateSession:output_type -> codegen.v1.CreateSessionResponse
	4,  // 16: codegen.v1.SessionManagement.DestroySession:output_type -> codegen.v1.DestroySessionResponse
	6,  // 17: codegen.v1.SessionManagement.CheckpointSession:output_type -> codegen.v1.CheckpointResponse
	9,  // 18: codegen.v1.SessionManagement.RestoreSession:output_type -> codegen.v1.RestoreResponse
	11, // 19: codegen.v1.SessionManagement.GetSessionStatus:output_type -> codegen.v1.SessionStatusResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_proto_v1_session_management_proto_init() }
func file_api_proto_v1_session_management_proto_init() {
	if File_api_proto_v1_session_management_proto != nil {
		return
	}
	file_api_proto_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_session_management_proto_rawDesc), len(file_api_proto_v1_session_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_session_management_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_session_management_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_session_management_proto_msgTypes,
	}.Build()
	File_api_proto_v1_session_management_proto = out.File
	file_api_proto_v1_session_management_proto_goTypes = nil
	file_api_proto_v1_session_management_proto_depIdxs = nil
}
