// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: api/proto/v1/task_execution.proto

package protov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskExecution_ExecuteTask_FullMethodName   = "/codegen.v1.TaskExecution/ExecuteTask"
	TaskExecution_CancelTask_FullMethodName    = "/codegen.v1.TaskExecution/CancelTask"
	TaskExecution_GetTaskStatus_FullMethodName = "/codegen.v1.TaskExecution/GetTaskStatus"
)

// TaskExecutionClient is the client API for TaskExecution service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TaskExecution handles tool execution requests
type TaskExecutionClient interface {
	// Execute a tool operation (supports streaming logs)
	ExecuteTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskResponse], error)
	// Cancel a running task
	CancelTask(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error)
	// Query task status
	GetTaskStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type taskExecutionClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskExecutionClient(cc grpc.ClientConnInterface) TaskExecutionClient {
	return &taskExecutionClient{cc}
}

func (c *taskExecutionClient) ExecuteTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskExecution_ServiceDesc.Streams[0], TaskExecution_ExecuteTask_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TaskRequest, TaskResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskExecution_ExecuteTaskClient = grpc.ServerStreamingClient[TaskResponse]

func (c *taskExecutionClient) CancelTask(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, TaskExecution_CancelTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskExecutionClient) GetTaskStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, TaskExecution_GetTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskExecutionServer is the server API for TaskExecution service.
// All implementations must embed UnimplementedTaskExecutionServer
// for forward compatibility.
//
// TaskExecution handles tool execution requests
type TaskExecutionServer interface {
	// Execute a tool operation (supports streaming logs)
	ExecuteTask(*TaskRequest, grpc.ServerStreamingServer[TaskResponse]) error
	// Cancel a running task
	CancelTask(context.Context, *CancelRequest) (*CancelResponse, error)
	// Query task status
	GetTaskStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedTaskExecutionServer()
}

// UnimplementedTaskExecutionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskExecutionServer struct{}

func (UnimplementedTaskExecutionServer) ExecuteTask(*TaskRequest, grpc.ServerStreamingServer[TaskResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ExecuteTask not implemented")
}
func (UnimplementedTaskExecutionServer) CancelTask(context.Context, *CancelRequest) (*CancelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedTaskExecutionServer) GetTaskStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskStatus not implemented")
}
func (UnimplementedTaskExecutionServer) mustEmbedUnimplementedTaskExecutionServer() {}
func (UnimplementedTaskExecutionServer) testEmbeddedByValue()                       {}

// UnsafeTaskExecutionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskExecutionServer will
// result in compilation errors.
type UnsafeTaskExecutionServer interface {
	mustEmbedUnimplementedTaskExecutionServer()
}

func RegisterTaskExecutionServer(s grpc.ServiceRegistrar, srv TaskExecutionServer) {
	// If the following call pancis, it indicates UnimplementedTaskExecutionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskExecution_ServiceDesc, srv)
}

func _TaskExecution_ExecuteTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TaskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TaskExecutionServer).ExecuteTask(m, &grpc.GenericServerStream[TaskRequest, TaskResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskExecution_ExecuteTaskServer = grpc.ServerStreamingServer[TaskResponse]

func _TaskExecution_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskExecutionServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskExecution_CancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskExecutionServer).CancelTask(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskExecution_GetTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskExecutionServer).GetTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskExecution_GetTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskExecutionServer).GetTaskStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskExecution_ServiceDesc is the grpc.ServiceDesc for TaskExecution service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskExecution_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "codegen.v1.TaskExecution",
	HandlerType: (*TaskExecutionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CancelTask",
			Handler:    _TaskExecution_CancelTask_Handler,
		},
		{
			MethodName: "GetTaskStatus",
			Handler:    _TaskExecution_GetTaskStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteTask",
			Handler:       _TaskExecution_ExecuteTask_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/v1/task_execution.proto",
}
