// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/proto/v1/task_execution.proto

package protov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogEntry_Level int32

const (
	LogEntry_LEVEL_UNSPECIFIED LogEntry_Level = 0
	LogEntry_LEVEL_DEBUG       LogEntry_Level = 1
	LogEntry_LEVEL_INFO        LogEntry_Level = 2
	LogEntry_LEVEL_WARN        LogEntry_Level = 3
	LogEntry_LEVEL_ERROR       LogEntry_Level = 4
)

// Enum value maps for LogEntry_Level.
var (
	LogEntry_Level_name = map[int32]string{
		0: "LEVEL_UNSPECIFIED",
		1: "LEVEL_DEBUG",
		2: "LEVEL_INFO",
		3: "LEVEL_WARN",
		4: "LEVEL_ERROR",
	}
	LogEntry_Level_value = map[string]int32{
		"LEVEL_UNSPECIFIED": 0,
		"LEVEL_DEBUG":       1,
		"LEVEL_INFO":        2,
		"LEVEL_WARN":        3,
		"LEVEL_ERROR":       4,
	}
)

func (x LogEntry_Level) Enum() *LogEntry_Level {
	p := new(LogEntry_Level)
	*p = x
	return p
}

func (x LogEntry_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogEntry_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_task_execution_proto_enumTypes[0].Descriptor()
}

func (LogEntry_Level) Type() protoreflect.EnumType {
	return &file_api_proto_v1_task_execution_proto_enumTypes[0]
}

func (x LogEntry_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogEntry_Level.Descriptor instead.
func (LogEntry_Level) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_task_execution_proto_rawDescGZIP(), []int{5, 0}
}

type TaskResult_Status int32

const (
	TaskResult_STATUS_UNSPECIFIED TaskResult_Status = 0
	TaskResult_STATUS_SUCCESS     TaskResult_Status = 1
	TaskResult_STATUS_FAILURE     TaskResult_Status = 2
	TaskResult_STATUS_TIMEOUT     TaskResult_Status = 3
	TaskResult_STATUS_CANCELLED   TaskResult_Status = 4
)

// Enum value maps for TaskResult_Status.
var (
	TaskResult_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_SUCCESS",
		2: "STATUS_FAILURE",
		3: "STATUS_TIMEOUT",
		4: "STATUS_CANCELLED",
	}
	TaskResult_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_SUCCESS":     1,
		"STATUS_FAILURE":     2,
		"STATUS_TIMEOUT":     3,
		"STATUS_CANCELLED":   4,
	}
)

func (x TaskResult_Status) Enum() *TaskResult_Status {
	p := new(TaskResult_Status)
	*p = x
	return p
}

func (x TaskResult_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskResult_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_task_execution_proto_enumTypes[1].Descriptor()
}

func (TaskResult_Status) Type() protoreflect.EnumType {
	return &file_api_proto_v1_task_execution_proto_enumTypes[1]
}

func (x TaskResult_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskResult_Status.Descriptor instead.
func (TaskResult_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_task_execution_proto_rawDescGZIP(), []int{6, 0}
}

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                   // Unique task identifier
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`          // Session ID (not worker registration session!)
	TypedRequest  *ToolRequest           `protobuf:"bytes,3,opt,name=typed_request,json=typedRequest,proto3" json:"typed_request,omitempty"` // Strongly-typed tool request
	Context       *TaskContext           `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	Constraints   *ExecutionConstraints  `protobuf:"bytes,5,opt,name=constraints,proto3" json:"constraints,omitempty"`
	Sequence      uint64                 `protobuf:"varint,6,opt,name=sequence,proto3" json:"sequence,omitempty"` // Monotonic sequence number for deduplication (0 = no tracking)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_api_proto_v1_task_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_execution_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TaskRequest) GetTypedRequest() *ToolRequest {
	if x != nil {
		return x.TypedRequest
	}
	return nil
}

func (x *TaskRequest) GetContext() *TaskContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *TaskRequest) GetConstraints() *ExecutionConstraints {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *TaskRequest) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type TaskContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`                                                               // Workspace identifier
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                                              // User/tenant identifier
	EnvVars       map[string]string      `protobuf:"bytes,3,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Environment overrides (merge with session env)
	Secrets       []string               `protobuf:"bytes,4,rep,name=secrets,proto3" json:"secrets,omitempty"`                                                                                          // Secret references (not values!)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskContext) Reset() {
	*x = TaskContext{}
	mi := &file_api_proto_v1_task_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskContext) ProtoMessage() {}

func (x *TaskContext) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskContext.ProtoReflect.Descriptor instead.
func (*TaskContext) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_execution_proto_rawDescGZIP(), []int{1}
}

func (x *TaskContext) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *TaskContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TaskContext) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *TaskContext) GetSecrets() []string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type ExecutionConstraints struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TimeoutSeconds int32                  `protobuf:"varint,1,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	MaxMemoryBytes int64                  `protobuf:"varint,2,opt,name=max_memory_bytes,json=maxMemoryBytes,proto3" json:"max_memory_bytes,omitempty"`
	MaxOutputBytes int64                  `protobuf:"varint,3,opt,name=max_output_bytes,json=maxOutputBytes,proto3" json:"max_output_bytes,omitempty"`
	AllowNetwork   bool                   `protobuf:"varint,4,opt,name=allow_network,json=allowNetwork,proto3" json:"allow_network,omitempty"`
	AllowedPaths   []string               `protobuf:"bytes,5,rep,name=allowed_paths,json=allowedPaths,proto3" json:"allowed_paths,omitempty"` // Path restrictions
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecutionConstraints) Reset() {
	*x = ExecutionConstraints{}
	mi := &file_api_proto_v1_task_execution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionConstraints) ProtoMessage() {}

func (x *ExecutionConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_execution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionConstraints.ProtoReflect.Descriptor instead.
func (*ExecutionConstraints) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_execution_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutionConstraints) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecutionConstraints) GetMaxMemoryBytes() int64 {
	if x != nil {
		return x.MaxMemoryBytes
	}
	return 0
}

func (x *ExecutionConstraints) GetMaxOutputBytes() int64 {
	if x != nil {
		return x.MaxOutputBytes
	}
	return 0
}

func (x *ExecutionConstraints) GetAllowNetwork() bool {
	if x != nil {
		return x.AllowNetwork
	}
	return false
}

func (x *ExecutionConstraints) GetAllowedPaths() []string {
	if x != nil {
		return x.AllowedPaths
	}
	return nil
}

type TaskResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TaskId string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TaskResponse_Progress
	//	*TaskResponse_Log
	//	*TaskResponse_Result
	//	*TaskResponse_Error
	Payload       isTaskResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_api_proto_v1_task_execution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_execution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_execution_proto_rawDescGZIP(), []int{3}
}

func (x *TaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResponse) GetPayload() isTaskResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TaskResponse) GetProgress() *ProgressUpdate {
	if x != nil {
		if x, ok := x.Payload.(*TaskResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *TaskResponse) GetLog() *LogEntry {
	if x != nil {
		if x, ok := x.Payload.(*TaskResponse_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *TaskResponse) GetResult() *TaskResult {
	if x != nil {
		if x, ok := x.Payload.(*TaskResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *TaskResponse) GetError() *TaskError {
	if x != nil {
		if x, ok := x.Payload.(*TaskResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isTaskResponse_Payload interface {
	isTaskResponse_Payload()
}

type TaskResponse_Progress struct {
	Progress *ProgressUpdate `protobuf:"bytes,2,opt,name=progress,proto3,oneof"`
}

type TaskResponse_Log struct {
	Log *LogEntry `protobuf:"bytes,3,opt,name=log,proto3,oneof"`
}

type TaskResponse_Result struct {
	Result *TaskResult `protobuf:"bytes,4,opt,name=result,proto3,oneof"`
}

type TaskResponse_Error struct {
	Error *TaskError `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

func (*TaskResponse_Progress) isTaskResponse_Payload() {}

func (*TaskResponse_Log) isTaskResponse_Payload() {}

func (*TaskResponse_Result) isTaskResponse_Payload() {}

func (*TaskResponse_Error) isTaskResponse_Payload() {}

type ProgressUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PercentComplete int32                  `protobuf:"varint,1,opt,name=percent_complete,json=percentComplete,proto3" json:"percent_complete,omitempty"`
	Stage           string                 `protobuf:"bytes,2,opt,name=stage,proto3" json:"stage,omitempty"` // e.g., "installing_packages", "running_tests"
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProgressUpdate) Reset() {
	*x = ProgressUpdate{}
	mi := &file_api_proto_v1_task_execution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdate) ProtoMessage() {}

func (x *ProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_execution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdate.ProtoReflect.Descriptor instead.
func (*ProgressUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_execution_proto_rawDescGZIP(), []int{4}
}

func (x *ProgressUpdate) GetPercentComplete() int32 {
	if x != nil {
		return x.PercentComplete
	}
	return 0
}

func (x *ProgressUpdate) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *ProgressUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         LogEntry_Level         `protobuf:"varint,1,opt,name=level,proto3,enum=codegen.v1.LogEntry_Level" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"` // e.g., "pytest", "pip"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_api_proto_v1_task_execution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_execution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_execution_proto_rawDescGZIP(), []int{5}
}

func (x *LogEntry) GetLevel() LogEntry_Level {
	if x != nil {
		return x.Level
	}
	return LogEntry_LEVEL_UNSPECIFIED
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *LogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        TaskResult_Status      `protobuf:"varint,1,opt,name=status,proto3,enum=codegen.v1.TaskResult_Status" json:"status,omitempty"`
	TypedResponse *ToolResponse          `protobuf:"bytes,2,opt,name=typed_response,json=typedResponse,proto3" json:"typed_response,omitempty"` // Strongly-typed tool response
	Artifacts     []string               `protobuf:"bytes,3,rep,name=artifacts,proto3" json:"artifacts,omitempty"`                              // Artifact IDs/URLs
	Metadata      *ExecutionMetadata     `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_api_proto_v1_task_execution_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_execution_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_execution_proto_rawDescGZIP(), []int{6}
}

func (x *TaskResult) GetStatus() TaskResult_Status {
	if x != nil {
		return x.Status
	}
	return TaskResult_STATUS_UNSPECIFIED
}

func (x *TaskResult) GetTypedResponse() *ToolResponse {
	if x != nil {
		return x.TypedResponse
	}
	return nil
}

func (x *TaskResult) GetArtifacts() []string {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *TaskResult) GetMetadata() *ExecutionMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ExecutionMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTimeMs   int64                  `protobuf:"varint,1,opt,name=start_time_ms,json=startTimeMs,proto3" json:"start_time_ms,omitempty"`
	EndTimeMs     int64                  `protobuf:"varint,2,opt,name=end_time_ms,json=endTimeMs,proto3" json:"end_time_ms,omitempty"`
	DurationMs    int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	PeakUsage     *ResourceUsage         `protobuf:"bytes,4,opt,name=peak_usage,json=peakUsage,proto3" json:"peak_usage,omitempty"`
	ExitCode      int32                  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"` // For shell/exec operations
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionMetadata) Reset() {
	*x = ExecutionMetadata{}
	mi := &file_api_proto_v1_task_execution_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionMetadata) ProtoMessage() {}

func (x *ExecutionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_execution_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionMetadata.ProtoReflect.Descriptor instead.
func (*ExecutionMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_execution_proto_rawDescGZIP(), []int{7}
}

func (x *ExecutionMetadata) GetStartTimeMs() int64 {
	if x != nil {
		return x.StartTimeMs
	}
	return 0
}

func (x *ExecutionMetadata) GetEndTimeMs() int64 {
	if x != nil {
		return x.EndTimeMs
	}
	return 0
}

func (x *ExecutionMetadata) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ExecutionMetadata) GetPeakUsage() *ResourceUsage {
	if x != nil {
		return x.PeakUsage
	}
	return nil
}

func (x *ExecutionMetadata) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type TaskError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // e.g., "EXEC_TIMEOUT", "PATH_VIOLATION"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"` // Stack trace, logs, etc.
	Retriable     bool                   `protobuf:"varint,4,opt,name=retriable,proto3" json:"retriable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskError) Reset() {
	*x = TaskError{}
	mi := &file_api_proto_v1_task_execution_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskError) ProtoMessage() {}

func (x *TaskError) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_execution_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskError.ProtoReflect.Descriptor instead.
func (*TaskError) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_execution_proto_rawDescGZIP(), []int{8}
}

func (x *TaskError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TaskError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskError) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *TaskError) GetRetriable() bool {
	if x != nil {
		return x.Retriable
	}
	return false
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_api_proto_v1_task_execution_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_execution_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_execution_proto_rawDescGZIP(), []int{9}
}

func (x *CancelRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CancelRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CancelRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cancelled     bool                   `protobuf:"varint,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // Current task state
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_api_proto_v1_task_execution_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_execution_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_execution_proto_rawDescGZIP(), []int{10}
}

func (x *CancelResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

func (x *CancelResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_proto_v1_task_execution_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_execution_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_execution_proto_rawDescGZIP(), []int{11}
}

func (x *StatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        TaskResult_Status      `protobuf:"varint,2,opt,name=status,proto3,enum=codegen.v1.TaskResult_Status" json:"status,omitempty"`
	Progress      *ProgressUpdate        `protobuf:"bytes,3,opt,name=progress,proto3" json:"progress,omitempty"`
	ElapsedMs     int64                  `protobuf:"varint,4,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_proto_v1_task_execution_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_execution_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_execution_proto_rawDescGZIP(), []int{12}
}

func (x *StatusResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StatusResponse) GetStatus() TaskResult_Status {
	if x != nil {
		return x.Status
	}
	return TaskResult_STATUS_UNSPECIFIED
}

func (x *StatusResponse) GetProgress() *ProgressUpdate {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *StatusResponse) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

var File_api_proto_v1_task_execution_proto protoreflect.FileDescriptor

const file_api_proto_v1_task_execution_proto_rawDesc = "" +
	"\n" +
	"!api/proto/v1/task_execution.proto\x12\n" +
	"codegen.v1\x1a\x19api/proto/v1/common.proto\x1a\x18api/proto/v1/tools.proto\"\x96\x02\n" +
	"\vTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12<\n" +
	"\rtyped_request\x18\x03 \x01(\v2\x17.codegen.v1.ToolRequestR\ftypedRequest\x121\n" +
	"\acontext\x18\x04 \x01(\v2\x17.codegen.v1.TaskContextR\acontext\x12B\n" +
	"\vconstraints\x18\x05 \x01(\v2 .codegen.v1.ExecutionConstraintsR\vconstraints\x12\x1a\n" +
	"\bsequence\x18\x06 \x01(\x04R\bsequence\"\xe0\x01\n" +
	"\vTaskContext\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12?\n" +
	"\benv_vars\x18\x03 \x03(\v2$.codegen.v1.TaskContext.EnvVarsEntryR\aenvVars\x12\x18\n" +
	"\asecrets\x18\x04 \x03(\tR\asecrets\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdd\x01\n" +
	"\x14ExecutionConstraints\x12'\n" +
	"\x0ftimeout_seconds\x18\x01 \x01(\x05R\x0etimeoutSeconds\x12(\n" +
	"\x10max_memory_bytes\x18\x02 \x01(\x03R\x0emaxMemoryBytes\x12(\n" +
	"\x10max_output_bytes\x18\x03 \x01(\x03R\x0emaxOutputBytes\x12#\n" +
	"\rallow_network\x18\x04 \x01(\bR\fallowNetwork\x12#\n" +
	"\rallowed_paths\x18\x05 \x03(\tR\fallowedPaths\"\xf7\x01\n" +
	"\fTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x128\n" +
	"\bprogress\x18\x02 \x01(\v2\x1a.codegen.v1.ProgressUpdateH\x00R\bprogress\x12(\n" +
	"\x03log\x18\x03 \x01(\v2\x14.codegen.v1.LogEntryH\x00R\x03log\x120\n" +
	"\x06result\x18\x04 \x01(\v2\x16.codegen.v1.TaskResultH\x00R\x06result\x12-\n" +
	"\x05error\x18\x05 \x01(\v2\x15.codegen.v1.TaskErrorH\x00R\x05errorB\t\n" +
	"\apayload\"k\n" +
	"\x0eProgressUpdate\x12)\n" +
	"\x10percent_complete\x18\x01 \x01(\x05R\x0fpercentComplete\x12\x14\n" +
	"\x05stage\x18\x02 \x01(\tR\x05stage\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xf3\x01\n" +
	"\bLogEntry\x120\n" +
	"\x05level\x18\x01 \x01(\x0e2\x1a.codegen.v1.LogEntry.LevelR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"`\n" +
	"\x05Level\x12\x15\n" +
	"\x11LEVEL_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vLEVEL_DEBUG\x10\x01\x12\x0e\n" +
	"\n" +
	"LEVEL_INFO\x10\x02\x12\x0e\n" +
	"\n" +
	"LEVEL_WARN\x10\x03\x12\x0f\n" +
	"\vLEVEL_ERROR\x10\x04\"\xd1\x02\n" +
	"\n" +
	"TaskResult\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.codegen.v1.TaskResult.StatusR\x06status\x12?\n" +
	"\x0etyped_response\x18\x02 \x01(\v2\x18.codegen.v1.ToolResponseR\rtypedResponse\x12\x1c\n" +
	"\tartifacts\x18\x03 \x03(\tR\tartifacts\x129\n" +
	"\bmetadata\x18\x04 \x01(\v2\x1d.codegen.v1.ExecutionMetadataR\bmetadata\"r\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_SUCCESS\x10\x01\x12\x12\n" +
	"\x0eSTATUS_FAILURE\x10\x02\x12\x12\n" +
	"\x0eSTATUS_TIMEOUT\x10\x03\x12\x14\n" +
	"\x10STATUS_CANCELLED\x10\x04\"\xcf\x01\n" +
	"\x11ExecutionMetadata\x12\"\n" +
	"\rstart_time_ms\x18\x01 \x01(\x03R\vstartTimeMs\x12\x1e\n" +
	"\vend_time_ms\x18\x02 \x01(\x03R\tendTimeMs\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\x128\n" +
	"\n" +
	"peak_usage\x18\x04 \x01(\v2\x19.codegen.v1.ResourceUsageR\tpeakUsage\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\"q\n" +
	"\tTaskError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\x12\x1c\n" +
	"\tretriable\x18\x04 \x01(\bR\tretriable\"_\n" +
	"\rCancelRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"D\n" +
	"\x0eCancelResponse\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\bR\tcancelled\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"G\n" +
	"\rStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\xb7\x01\n" +
	"\x0eStatusResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.codegen.v1.TaskResult.StatusR\x06status\x126\n" +
	"\bprogress\x18\x03 \x01(\v2\x1a.codegen.v1.ProgressUpdateR\bprogress\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x04 \x01(\x03R\telapsedMs2\xe0\x01\n" +
	"\rTaskExecution\x12B\n" +
	"\vExecuteTask\x12\x17.codegen.v1.TaskRequest\x1a\x18.codegen.v1.TaskResponse0\x01\x12C\n" +
	"\n" +
	"CancelTask\x12\x19.codegen.v1.CancelRequest\x1a\x1a.codegen.v1.CancelResponse\x12F\n" +
	"\rGetTaskStatus\x12\x19.codegen.v1.StatusRequest\x1a\x1a.codegen.v1.StatusResponseB9Z7github.com/altairalabs/codegen-mcp/api/proto/v1;protov1b\x06proto3"

var (
	file_api_proto_v1_task_execution_proto_rawDescOnce sync.Once
	file_api_proto_v1_task_execution_proto_rawDescData []byte
)

func file_api_proto_v1_task_execution_proto_rawDescGZIP() []byte {
	file_api_proto_v1_task_execution_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_task_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_task_execution_proto_rawDesc), len(file_api_proto_v1_task_execution_proto_rawDesc)))
	})
	return file_api_proto_v1_task_execution_proto_rawDescData
}

var file_api_proto_v1_task_execution_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_v1_task_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_v1_task_execution_proto_goTypes = []any{
	(LogEntry_Level)(0),          // 0: codegen.v1.LogEntry.Level
	(TaskResult_Status)(0),       // 1: codegen.v1.TaskResult.Status
	(*TaskRequest)(nil),          // 2: codegen.v1.TaskRequest
	(*TaskContext)(nil),          // 3: codegen.v1.TaskContext
	(*ExecutionConstraints)(nil), // 4: codegen.v1.ExecutionConstraints
	(*TaskResponse)(nil),         // 5: codegen.v1.TaskResponse
	(*ProgressUpdate)(nil),       // 6: codegen.v1.ProgressUpdate
	(*LogEntry)(nil),             // 7: codegen.v1.LogEntry
	(*TaskResult)(nil),           // 8: codegen.v1.TaskResult
	(*ExecutionMetadata)(nil),    // 9: codegen.v1.ExecutionMetadata
	(*TaskError)(nil),            // 10: codegen.v1.TaskError
	(*CancelRequest)(nil),        // 11: codegen.v1.CancelRequest
	(*CancelResponse)(nil),       // 12: codegen.v1.CancelResponse
	(*StatusRequest)(nil),        // 13: codegen.v1.StatusRequest
	(*StatusResponse)(nil),       // 14: codegen.v1.StatusResponse
	nil,                          // 15: codegen.v1.TaskContext.EnvVarsEntry
	(*ToolRequest)(nil),          // 16: codegen.v1.ToolRequest
	(*ToolResponse)(nil),         // 17: codegen.v1.ToolResponse
	(*ResourceUsage)(nil),        // 18: codegen.v1.ResourceUsage
}
var file_api_proto_v1_task_execution_proto_depIdxs = []int32{
	16, // 0: codegen.v1.TaskRequest.typed_request:type_name -> codegen.v1.ToolRequest
	3,  // 1: codegen.v1.TaskRequest.context:type_name -> codegen.v1.TaskContext
	4,  // 2: codegen.v1.TaskRequest.constraints:type_name -> codegen.v1.ExecutionConstraints
	15, // 3: codegen.v1.TaskContext.env_vars:type_name -> codegen.v1.TaskContext.EnvVarsEntry
	6,  // 4: codegen.v1.TaskResponse.progress:type_name -> codegen.v1.ProgressUpdate
	7,  // 5: codegen.v1.TaskResponse.log:type_name -> codegen.v1.LogEntry
	8,  // 6: codegen.v1.TaskResponse.result:type_name -> codegen.v1.TaskResult
	10, // 7: codegen.v1.TaskResponse.error:type_name -> codegen.v1.TaskError
	0,  // 8: codegen.v1.LogEntry.level:type_name -> codegen.v1.LogEntry.Level
	1,  // 9: codegen.v1.TaskResult.status:type_name -> codegen.v1.TaskResult.Status
	17, // 10: codegen.v1.TaskResult.typed_response:type_name -> codegen.v1.ToolResponse
	9,  // 11: codegen.v1.TaskResult.metadata:type_name -> codegen.v1.ExecutionMetadata
	18, // 12: codegen.v1.ExecutionMetadata.peak_usage:type_name -> codegen.v1.ResourceUsage
	1,  // 13: codegen.v1.StatusResponse.status:type_name -> codegen.v1.TaskResult.Status
	6,  // 14: codegen.v1.StatusResponse.progress:type_name -> codegen.v1.ProgressUpdate
	2,  // 15: codegen.v1.TaskExecution.ExecuteTask:input_type -> codegen.v1.TaskRequest
	11, // 16: codegen.v1.TaskExecution.CancelTask:input_type -> codegen.v1.CancelRequest
	13, // 17: codegen.v1.TaskExecution.GetTaskStatus:input_type -> codegen.v1.StatusRequest
	5,  // 18: codegen.v1.TaskExecution.ExecuteTask:output_type -> codegen.v1.TaskResponse
	12, // 19: codegen.v1.TaskExecution.CancelTask:output_type -> codegen.v1.CancelResponse
	14, // 20: codegen.v1.TaskExecution.GetTaskStatus:output_type -> codegen.v1.StatusResponse
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_api_proto_v1_task_execution_proto_init() }
func file_api_proto_v1_task_execution_proto_init() {
	if File_api_proto_v1_task_execution_proto != nil {
		return
	}
	file_api_proto_v1_common_proto_init()
	file_api_proto_v1_tools_proto_init()
	file_api_proto_v1_task_execution_proto_msgTypes[3].OneofWrappers = []any{
		(*TaskResponse_Progress)(nil),
		(*TaskResponse_Log)(nil),
		(*TaskResponse_Result)(nil),
		(*TaskResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_task_execution_proto_rawDesc), len(file_api_proto_v1_task_execution_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_task_execution_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_task_execution_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_task_execution_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_task_execution_proto_msgTypes,
	}.Build()
	File_api_proto_v1_task_execution_proto = out.File
	file_api_proto_v1_task_execution_proto_goTypes = nil
	file_api_proto_v1_task_execution_proto_depIdxs = nil
}
