// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/proto/v1/tools.proto

package protov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,100,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Optional arbitrary metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_api_proto_v1_tools_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tools_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tools_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,100,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Optional arbitrary metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_api_proto_v1_tools_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tools_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tools_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type FsReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // Path to file (relative to workspace root)
	Metadata      map[string]string      `protobuf:"bytes,100,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsReadRequest) Reset() {
	*x = FsReadRequest{}
	mi := &file_api_proto_v1_tools_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsReadRequest) ProtoMessage() {}

func (x *FsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tools_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsReadRequest.ProtoReflect.Descriptor instead.
func (*FsReadRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tools_proto_rawDescGZIP(), []int{2}
}

func (x *FsReadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FsReadRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type FsReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contents      string                 `protobuf:"bytes,1,opt,name=contents,proto3" json:"contents,omitempty"`                     // File contents
	SizeBytes     int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"` // File size
	Encoding      string                 `protobuf:"bytes,3,opt,name=encoding,proto3" json:"encoding,omitempty"`                     // Detected encoding (e.g., "utf-8")
	Metadata      map[string]string      `protobuf:"bytes,100,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsReadResponse) Reset() {
	*x = FsReadResponse{}
	mi := &file_api_proto_v1_tools_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsReadResponse) ProtoMessage() {}

func (x *FsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tools_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsReadResponse.ProtoReflect.Descriptor instead.
func (*FsReadResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tools_proto_rawDescGZIP(), []int{3}
}

func (x *FsReadResponse) GetContents() string {
	if x != nil {
		return x.Contents
	}
	return ""
}

func (x *FsReadResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FsReadResponse) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *FsReadResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type FsWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                                // Path to file (relative to workspace root)
	Contents      string                 `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`                        // Content to write
	CreateDirs    bool                   `protobuf:"varint,3,opt,name=create_dirs,json=createDirs,proto3" json:"create_dirs,omitempty"` // Create parent directories if needed
	Metadata      map[string]string      `protobuf:"bytes,100,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsWriteRequest) Reset() {
	*x = FsWriteRequest{}
	mi := &file_api_proto_v1_tools_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsWriteRequest) ProtoMessage() {}

func (x *FsWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tools_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsWriteRequest.ProtoReflect.Descriptor instead.
func (*FsWriteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tools_proto_rawDescGZIP(), []int{4}
}

func (x *FsWriteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FsWriteRequest) GetContents() string {
	if x != nil {
		return x.Contents
	}
	return ""
}

func (x *FsWriteRequest) GetCreateDirs() bool {
	if x != nil {
		return x.CreateDirs
	}
	return false
}

func (x *FsWriteRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type FsWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                                      // Path that was written
	BytesWritten  int64                  `protobuf:"varint,2,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"` // Number of bytes written
	Metadata      map[string]string      `protobuf:"bytes,100,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsWriteResponse) Reset() {
	*x = FsWriteResponse{}
	mi := &file_api_proto_v1_tools_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsWriteResponse) ProtoMessage() {}

func (x *FsWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tools_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsWriteResponse.ProtoReflect.Descriptor instead.
func (*FsWriteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tools_proto_rawDescGZIP(), []int{5}
}

func (x *FsWriteResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FsWriteResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *FsWriteResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type FsListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`            // Directory path (optional, defaults to root)
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"` // List recursively
	Pattern       string                 `protobuf:"bytes,3,opt,name=pattern,proto3" json:"pattern,omitempty"`      // Optional glob pattern filter
	Metadata      map[string]string      `protobuf:"bytes,100,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsListRequest) Reset() {
	*x = FsListRequest{}
	mi := &file_api_proto_v1_tools_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsListRequest) ProtoMessage() {}

func (x *FsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tools_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsListRequest.ProtoReflect.Descriptor instead.
func (*FsListRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tools_proto_rawDescGZIP(), []int{6}
}

func (x *FsListRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FsListRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *FsListRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *FsListRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type FsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // Total number of files
	Metadata      map[string]string      `protobuf:"bytes,100,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsListResponse) Reset() {
	*x = FsListResponse{}
	mi := &file_api_proto_v1_tools_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsListResponse) ProtoMessage() {}

func (x *FsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tools_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsListResponse.ProtoReflect.Descriptor instead.
func (*FsListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tools_proto_rawDescGZIP(), []int{7}
}

func (x *FsListResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *FsListResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *FsListResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type FileInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Path           string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                                              // Relative path
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                              // File name
	SizeBytes      int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`                  // File size
	IsDirectory    bool                   `protobuf:"varint,4,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`            // Is this a directory?
	ModifiedTimeMs int64                  `protobuf:"varint,5,opt,name=modified_time_ms,json=modifiedTimeMs,proto3" json:"modified_time_ms,omitempty"` // Last modified time
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_api_proto_v1_tools_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tools_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tools_proto_rawDescGZIP(), []int{8}
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileInfo) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

func (x *FileInfo) GetModifiedTimeMs() int64 {
	if x != nil {
		return x.ModifiedTimeMs
	}
	return 0
}

type RunPythonRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*RunPythonRequest_Code
	//	*RunPythonRequest_File
	Source         isRunPythonRequest_Source `protobuf_oneof:"source"`
	Args           []string                  `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`                                                                                                // Command-line arguments (if running file)
	EnvVars        map[string]string         `protobuf:"bytes,4,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional environment variables
	TimeoutSeconds int32                     `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`                                                     // Execution timeout
	Metadata       map[string]string         `protobuf:"bytes,100,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunPythonRequest) Reset() {
	*x = RunPythonRequest{}
	mi := &file_api_proto_v1_tools_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPythonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPythonRequest) ProtoMessage() {}

func (x *RunPythonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tools_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPythonRequest.ProtoReflect.Descriptor instead.
func (*RunPythonRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tools_proto_rawDescGZIP(), []int{9}
}

func (x *RunPythonRequest) GetSource() isRunPythonRequest_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *RunPythonRequest) GetCode() string {
	if x != nil {
		if x, ok := x.Source.(*RunPythonRequest_Code); ok {
			return x.Code
		}
	}
	return ""
}

func (x *RunPythonRequest) GetFile() string {
	if x != nil {
		if x, ok := x.Source.(*RunPythonRequest_File); ok {
			return x.File
		}
	}
	return ""
}

func (x *RunPythonRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *RunPythonRequest) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *RunPythonRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *RunPythonRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type isRunPythonRequest_Source interface {
	isRunPythonRequest_Source()
}

type RunPythonRequest_Code struct {
	Code string `protobuf:"bytes,1,opt,name=code,proto3,oneof"` // Python code to execute
}

type RunPythonRequest_File struct {
	File string `protobuf:"bytes,2,opt,name=file,proto3,oneof"` // Path to Python file to execute
}

func (*RunPythonRequest_Code) isRunPythonRequest_Source() {}

func (*RunPythonRequest_File) isRunPythonRequest_Source() {}

type RunPythonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        string                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`                            // Standard output
	Stderr        string                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`                            // Standard error
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`       // Exit code
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"` // Execution duration
	TimedOut      bool                   `protobuf:"varint,5,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`       // Whether execution timed out
	Metadata      map[string]string      `protobuf:"bytes,100,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunPythonResponse) Reset() {
	*x = RunPythonResponse{}
	mi := &file_api_proto_v1_tools_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPythonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPythonResponse) ProtoMessage() {}

func (x *RunPythonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tools_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPythonResponse.ProtoReflect.Descriptor instead.
func (*RunPythonResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tools_proto_rawDescGZIP(), []int{10}
}

func (x *RunPythonResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *RunPythonResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *RunPythonResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *RunPythonResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *RunPythonResponse) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

func (x *RunPythonResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PkgInstallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packages      []string               `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`                 // Package specifiers (e.g., "requests==2.28.0")
	Upgrade       bool                   `protobuf:"varint,2,opt,name=upgrade,proto3" json:"upgrade,omitempty"`                  // Upgrade if already installed
	IndexUrl      string                 `protobuf:"bytes,3,opt,name=index_url,json=indexUrl,proto3" json:"index_url,omitempty"` // Custom PyPI index URL
	NoDeps        bool                   `protobuf:"varint,4,opt,name=no_deps,json=noDeps,proto3" json:"no_deps,omitempty"`      // Don't install dependencies
	Metadata      map[string]string      `protobuf:"bytes,100,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PkgInstallRequest) Reset() {
	*x = PkgInstallRequest{}
	mi := &file_api_proto_v1_tools_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PkgInstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PkgInstallRequest) ProtoMessage() {}

func (x *PkgInstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tools_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PkgInstallRequest.ProtoReflect.Descriptor instead.
func (*PkgInstallRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tools_proto_rawDescGZIP(), []int{11}
}

func (x *PkgInstallRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *PkgInstallRequest) GetUpgrade() bool {
	if x != nil {
		return x.Upgrade
	}
	return false
}

func (x *PkgInstallRequest) GetIndexUrl() string {
	if x != nil {
		return x.IndexUrl
	}
	return ""
}

func (x *PkgInstallRequest) GetNoDeps() bool {
	if x != nil {
		return x.NoDeps
	}
	return false
}

func (x *PkgInstallRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PkgInstallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Installed     []*PackageInfo         `protobuf:"bytes,1,rep,name=installed,proto3" json:"installed,omitempty"`                // Successfully installed packages
	Failed        []string               `protobuf:"bytes,2,rep,name=failed,proto3" json:"failed,omitempty"`                      // Packages that failed to install
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`                      // Full pip output
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"` // pip exit code
	Metadata      map[string]string      `protobuf:"bytes,100,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PkgInstallResponse) Reset() {
	*x = PkgInstallResponse{}
	mi := &file_api_proto_v1_tools_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PkgInstallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PkgInstallResponse) ProtoMessage() {}

func (x *PkgInstallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tools_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PkgInstallResponse.ProtoReflect.Descriptor instead.
func (*PkgInstallResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tools_proto_rawDescGZIP(), []int{12}
}

func (x *PkgInstallResponse) GetInstalled() []*PackageInfo {
	if x != nil {
		return x.Installed
	}
	return nil
}

func (x *PkgInstallResponse) GetFailed() []string {
	if x != nil {
		return x.Failed
	}
	return nil
}

func (x *PkgInstallResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *PkgInstallResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *PkgInstallResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PackageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`         // Package name
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`   // Installed version
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"` // Installation location
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageInfo) Reset() {
	*x = PackageInfo{}
	mi := &file_api_proto_v1_tools_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageInfo) ProtoMessage() {}

func (x *PackageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tools_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageInfo.ProtoReflect.Descriptor instead.
func (*PackageInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tools_proto_rawDescGZIP(), []int{13}
}

func (x *PackageInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackageInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PackageInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type ToolRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*ToolRequest_Echo
	//	*ToolRequest_FsRead
	//	*ToolRequest_FsWrite
	//	*ToolRequest_FsList
	//	*ToolRequest_RunPython
	//	*ToolRequest_PkgInstall
	Request       isToolRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolRequest) Reset() {
	*x = ToolRequest{}
	mi := &file_api_proto_v1_tools_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRequest) ProtoMessage() {}

func (x *ToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tools_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRequest.ProtoReflect.Descriptor instead.
func (*ToolRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tools_proto_rawDescGZIP(), []int{14}
}

func (x *ToolRequest) GetRequest() isToolRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ToolRequest) GetEcho() *EchoRequest {
	if x != nil {
		if x, ok := x.Request.(*ToolRequest_Echo); ok {
			return x.Echo
		}
	}
	return nil
}

func (x *ToolRequest) GetFsRead() *FsReadRequest {
	if x != nil {
		if x, ok := x.Request.(*ToolRequest_FsRead); ok {
			return x.FsRead
		}
	}
	return nil
}

func (x *ToolRequest) GetFsWrite() *FsWriteRequest {
	if x != nil {
		if x, ok := x.Request.(*ToolRequest_FsWrite); ok {
			return x.FsWrite
		}
	}
	return nil
}

func (x *ToolRequest) GetFsList() *FsListRequest {
	if x != nil {
		if x, ok := x.Request.(*ToolRequest_FsList); ok {
			return x.FsList
		}
	}
	return nil
}

func (x *ToolRequest) GetRunPython() *RunPythonRequest {
	if x != nil {
		if x, ok := x.Request.(*ToolRequest_RunPython); ok {
			return x.RunPython
		}
	}
	return nil
}

func (x *ToolRequest) GetPkgInstall() *PkgInstallRequest {
	if x != nil {
		if x, ok := x.Request.(*ToolRequest_PkgInstall); ok {
			return x.PkgInstall
		}
	}
	return nil
}

type isToolRequest_Request interface {
	isToolRequest_Request()
}

type ToolRequest_Echo struct {
	Echo *EchoRequest `protobuf:"bytes,1,opt,name=echo,proto3,oneof"`
}

type ToolRequest_FsRead struct {
	FsRead *FsReadRequest `protobuf:"bytes,2,opt,name=fs_read,json=fsRead,proto3,oneof"`
}

type ToolRequest_FsWrite struct {
	FsWrite *FsWriteRequest `protobuf:"bytes,3,opt,name=fs_write,json=fsWrite,proto3,oneof"`
}

type ToolRequest_FsList struct {
	FsList *FsListRequest `protobuf:"bytes,4,opt,name=fs_list,json=fsList,proto3,oneof"`
}

type ToolRequest_RunPython struct {
	RunPython *RunPythonRequest `protobuf:"bytes,5,opt,name=run_python,json=runPython,proto3,oneof"`
}

type ToolRequest_PkgInstall struct {
	PkgInstall *PkgInstallRequest `protobuf:"bytes,6,opt,name=pkg_install,json=pkgInstall,proto3,oneof"`
}

func (*ToolRequest_Echo) isToolRequest_Request() {}

func (*ToolRequest_FsRead) isToolRequest_Request() {}

func (*ToolRequest_FsWrite) isToolRequest_Request() {}

func (*ToolRequest_FsList) isToolRequest_Request() {}

func (*ToolRequest_RunPython) isToolRequest_Request() {}

func (*ToolRequest_PkgInstall) isToolRequest_Request() {}

type ToolResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ToolResponse_Echo
	//	*ToolResponse_FsRead
	//	*ToolResponse_FsWrite
	//	*ToolResponse_FsList
	//	*ToolResponse_RunPython
	//	*ToolResponse_PkgInstall
	Response      isToolResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResponse) Reset() {
	*x = ToolResponse{}
	mi := &file_api_proto_v1_tools_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResponse) ProtoMessage() {}

func (x *ToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tools_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResponse.ProtoReflect.Descriptor instead.
func (*ToolResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tools_proto_rawDescGZIP(), []int{15}
}

func (x *ToolResponse) GetResponse() isToolResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ToolResponse) GetEcho() *EchoResponse {
	if x != nil {
		if x, ok := x.Response.(*ToolResponse_Echo); ok {
			return x.Echo
		}
	}
	return nil
}

func (x *ToolResponse) GetFsRead() *FsReadResponse {
	if x != nil {
		if x, ok := x.Response.(*ToolResponse_FsRead); ok {
			return x.FsRead
		}
	}
	return nil
}

func (x *ToolResponse) GetFsWrite() *FsWriteResponse {
	if x != nil {
		if x, ok := x.Response.(*ToolResponse_FsWrite); ok {
			return x.FsWrite
		}
	}
	return nil
}

func (x *ToolResponse) GetFsList() *FsListResponse {
	if x != nil {
		if x, ok := x.Response.(*ToolResponse_FsList); ok {
			return x.FsList
		}
	}
	return nil
}

func (x *ToolResponse) GetRunPython() *RunPythonResponse {
	if x != nil {
		if x, ok := x.Response.(*ToolResponse_RunPython); ok {
			return x.RunPython
		}
	}
	return nil
}

func (x *ToolResponse) GetPkgInstall() *PkgInstallResponse {
	if x != nil {
		if x, ok := x.Response.(*ToolResponse_PkgInstall); ok {
			return x.PkgInstall
		}
	}
	return nil
}

type isToolResponse_Response interface {
	isToolResponse_Response()
}

type ToolResponse_Echo struct {
	Echo *EchoResponse `protobuf:"bytes,1,opt,name=echo,proto3,oneof"`
}

type ToolResponse_FsRead struct {
	FsRead *FsReadResponse `protobuf:"bytes,2,opt,name=fs_read,json=fsRead,proto3,oneof"`
}

type ToolResponse_FsWrite struct {
	FsWrite *FsWriteResponse `protobuf:"bytes,3,opt,name=fs_write,json=fsWrite,proto3,oneof"`
}

type ToolResponse_FsList struct {
	FsList *FsListResponse `protobuf:"bytes,4,opt,name=fs_list,json=fsList,proto3,oneof"`
}

type ToolResponse_RunPython struct {
	RunPython *RunPythonResponse `protobuf:"bytes,5,opt,name=run_python,json=runPython,proto3,oneof"`
}

type ToolResponse_PkgInstall struct {
	PkgInstall *PkgInstallResponse `protobuf:"bytes,6,opt,name=pkg_install,json=pkgInstall,proto3,oneof"`
}

func (*ToolResponse_Echo) isToolResponse_Response() {}

func (*ToolResponse_FsRead) isToolResponse_Response() {}

func (*ToolResponse_FsWrite) isToolResponse_Response() {}

func (*ToolResponse_FsList) isToolResponse_Response() {}

func (*ToolResponse_RunPython) isToolResponse_Response() {}

func (*ToolResponse_PkgInstall) isToolResponse_Response() {}

var File_api_proto_v1_tools_proto protoreflect.FileDescriptor

const file_api_proto_v1_tools_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/v1/tools.proto\x12\n" +
	"codegen.v1\"\xa7\x01\n" +
	"\vEchoRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12A\n" +
	"\bmetadata\x18d \x03(\v2%.codegen.v1.EchoRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa9\x01\n" +
	"\fEchoResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12B\n" +
	"\bmetadata\x18d \x03(\v2&.codegen.v1.EchoResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa5\x01\n" +
	"\rFsReadRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12C\n" +
	"\bmetadata\x18d \x03(\v2'.codegen.v1.FsReadRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xea\x01\n" +
	"\x0eFsReadResponse\x12\x1a\n" +
	"\bcontents\x18\x01 \x01(\tR\bcontents\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12\x1a\n" +
	"\bencoding\x18\x03 \x01(\tR\bencoding\x12D\n" +
	"\bmetadata\x18d \x03(\v2(.codegen.v1.FsReadResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe4\x01\n" +
	"\x0eFsWriteRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\bcontents\x18\x02 \x01(\tR\bcontents\x12\x1f\n" +
	"\vcreate_dirs\x18\x03 \x01(\bR\n" +
	"createDirs\x12D\n" +
	"\bmetadata\x18d \x03(\v2(.codegen.v1.FsWriteRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xce\x01\n" +
	"\x0fFsWriteResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12#\n" +
	"\rbytes_written\x18\x02 \x01(\x03R\fbytesWritten\x12E\n" +
	"\bmetadata\x18d \x03(\v2).codegen.v1.FsWriteResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdd\x01\n" +
	"\rFsListRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\x12\x18\n" +
	"\apattern\x18\x03 \x01(\tR\apattern\x12C\n" +
	"\bmetadata\x18d \x03(\v2'.codegen.v1.FsListRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe0\x01\n" +
	"\x0eFsListResponse\x12*\n" +
	"\x05files\x18\x01 \x03(\v2\x14.codegen.v1.FileInfoR\x05files\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12D\n" +
	"\bmetadata\x18d \x03(\v2(.codegen.v1.FsListResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12!\n" +
	"\fis_directory\x18\x04 \x01(\bR\visDirectory\x12(\n" +
	"\x10modified_time_ms\x18\x05 \x01(\x03R\x0emodifiedTimeMs\"\x8c\x03\n" +
	"\x10RunPythonRequest\x12\x14\n" +
	"\x04code\x18\x01 \x01(\tH\x00R\x04code\x12\x14\n" +
	"\x04file\x18\x02 \x01(\tH\x00R\x04file\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12D\n" +
	"\benv_vars\x18\x04 \x03(\v2).codegen.v1.RunPythonRequest.EnvVarsEntryR\aenvVars\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x12F\n" +
	"\bmetadata\x18d \x03(\v2*.codegen.v1.RunPythonRequest.MetadataEntryR\bmetadata\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06source\"\xa4\x02\n" +
	"\x11RunPythonResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12\x1b\n" +
	"\ttimed_out\x18\x05 \x01(\bR\btimedOut\x12G\n" +
	"\bmetadata\x18d \x03(\v2+.codegen.v1.RunPythonResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x02\n" +
	"\x11PkgInstallRequest\x12\x1a\n" +
	"\bpackages\x18\x01 \x03(\tR\bpackages\x12\x18\n" +
	"\aupgrade\x18\x02 \x01(\bR\aupgrade\x12\x1b\n" +
	"\tindex_url\x18\x03 \x01(\tR\bindexUrl\x12\x17\n" +
	"\ano_deps\x18\x04 \x01(\bR\x06noDeps\x12G\n" +
	"\bmetadata\x18d \x03(\v2+.codegen.v1.PkgInstallRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9f\x02\n" +
	"\x12PkgInstallResponse\x125\n" +
	"\tinstalled\x18\x01 \x03(\v2\x17.codegen.v1.PackageInfoR\tinstalled\x12\x16\n" +
	"\x06failed\x18\x02 \x03(\tR\x06failed\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12H\n" +
	"\bmetadata\x18d \x03(\v2,.codegen.v1.PkgInstallResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"W\n" +
	"\vPackageInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\"\xed\x02\n" +
	"\vToolRequest\x12-\n" +
	"\x04echo\x18\x01 \x01(\v2\x17.codegen.v1.EchoRequestH\x00R\x04echo\x124\n" +
	"\afs_read\x18\x02 \x01(\v2\x19.codegen.v1.FsReadRequestH\x00R\x06fsRead\x127\n" +
	"\bfs_write\x18\x03 \x01(\v2\x1a.codegen.v1.FsWriteRequestH\x00R\afsWrite\x124\n" +
	"\afs_list\x18\x04 \x01(\v2\x19.codegen.v1.FsListRequestH\x00R\x06fsList\x12=\n" +
	"\n" +
	"run_python\x18\x05 \x01(\v2\x1c.codegen.v1.RunPythonRequestH\x00R\trunPython\x12@\n" +
	"\vpkg_install\x18\x06 \x01(\v2\x1d.codegen.v1.PkgInstallRequestH\x00R\n" +
	"pkgInstallB\t\n" +
	"\arequest\"\xf5\x02\n" +
	"\fToolResponse\x12.\n" +
	"\x04echo\x18\x01 \x01(\v2\x18.codegen.v1.EchoResponseH\x00R\x04echo\x125\n" +
	"\afs_read\x18\x02 \x01(\v2\x1a.codegen.v1.FsReadResponseH\x00R\x06fsRead\x128\n" +
	"\bfs_write\x18\x03 \x01(\v2\x1b.codegen.v1.FsWriteResponseH\x00R\afsWrite\x125\n" +
	"\afs_list\x18\x04 \x01(\v2\x1a.codegen.v1.FsListResponseH\x00R\x06fsList\x12>\n" +
	"\n" +
	"run_python\x18\x05 \x01(\v2\x1d.codegen.v1.RunPythonResponseH\x00R\trunPython\x12A\n" +
	"\vpkg_install\x18\x06 \x01(\v2\x1e.codegen.v1.PkgInstallResponseH\x00R\n" +
	"pkgInstallB\n" +
	"\n" +
	"\bresponseB9Z7github.com/altairalabs/codegen-mcp/api/proto/v1;protov1b\x06proto3"

var (
	file_api_proto_v1_tools_proto_rawDescOnce sync.Once
	file_api_proto_v1_tools_proto_rawDescData []byte
)

func file_api_proto_v1_tools_proto_rawDescGZIP() []byte {
	file_api_proto_v1_tools_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_tools_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_tools_proto_rawDesc), len(file_api_proto_v1_tools_proto_rawDesc)))
	})
	return file_api_proto_v1_tools_proto_rawDescData
}

var file_api_proto_v1_tools_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_api_proto_v1_tools_proto_goTypes = []any{
	(*EchoRequest)(nil),        // 0: codegen.v1.EchoRequest
	(*EchoResponse)(nil),       // 1: codegen.v1.EchoResponse
	(*FsReadRequest)(nil),      // 2: codegen.v1.FsReadRequest
	(*FsReadResponse)(nil),     // 3: codegen.v1.FsReadResponse
	(*FsWriteRequest)(nil),     // 4: codegen.v1.FsWriteRequest
	(*FsWriteResponse)(nil),    // 5: codegen.v1.FsWriteResponse
	(*FsListRequest)(nil),      // 6: codegen.v1.FsListRequest
	(*FsListResponse)(nil),     // 7: codegen.v1.FsListResponse
	(*FileInfo)(nil),           // 8: codegen.v1.FileInfo
	(*RunPythonRequest)(nil),   // 9: codegen.v1.RunPythonRequest
	(*RunPythonResponse)(nil),  // 10: codegen.v1.RunPythonResponse
	(*PkgInstallRequest)(nil),  // 11: codegen.v1.PkgInstallRequest
	(*PkgInstallResponse)(nil), // 12: codegen.v1.PkgInstallResponse
	(*PackageInfo)(nil),        // 13: codegen.v1.PackageInfo
	(*ToolRequest)(nil),        // 14: codegen.v1.ToolRequest
	(*ToolResponse)(nil),       // 15: codegen.v1.ToolResponse
	nil,                        // 16: codegen.v1.EchoRequest.MetadataEntry
	nil,                        // 17: codegen.v1.EchoResponse.MetadataEntry
	nil,                        // 18: codegen.v1.FsReadRequest.MetadataEntry
	nil,                        // 19: codegen.v1.FsReadResponse.MetadataEntry
	nil,                        // 20: codegen.v1.FsWriteRequest.MetadataEntry
	nil,                        // 21: codegen.v1.FsWriteResponse.MetadataEntry
	nil,                        // 22: codegen.v1.FsListRequest.MetadataEntry
	nil,                        // 23: codegen.v1.FsListResponse.MetadataEntry
	nil,                        // 24: codegen.v1.RunPythonRequest.EnvVarsEntry
	nil,                        // 25: codegen.v1.RunPythonRequest.MetadataEntry
	nil,                        // 26: codegen.v1.RunPythonResponse.MetadataEntry
	nil,                        // 27: codegen.v1.PkgInstallRequest.MetadataEntry
	nil,                        // 28: codegen.v1.PkgInstallResponse.MetadataEntry
}
var file_api_proto_v1_tools_proto_depIdxs = []int32{
	16, // 0: codegen.v1.EchoRequest.metadata:type_name -> codegen.v1.EchoRequest.MetadataEntry
	17, // 1: codegen.v1.EchoResponse.metadata:type_name -> codegen.v1.EchoResponse.MetadataEntry
	18, // 2: codegen.v1.FsReadRequest.metadata:type_name -> codegen.v1.FsReadRequest.MetadataEntry
	19, // 3: codegen.v1.FsReadResponse.metadata:type_name -> codegen.v1.FsReadResponse.MetadataEntry
	20, // 4: codegen.v1.FsWriteRequest.metadata:type_name -> codegen.v1.FsWriteRequest.MetadataEntry
	21, // 5: codegen.v1.FsWriteResponse.metadata:type_name -> codegen.v1.FsWriteResponse.MetadataEntry
	22, // 6: codegen.v1.FsListRequest.metadata:type_name -> codegen.v1.FsListRequest.MetadataEntry
	8,  // 7: codegen.v1.FsListResponse.files:type_name -> codegen.v1.FileInfo
	23, // 8: codegen.v1.FsListResponse.metadata:type_name -> codegen.v1.FsListResponse.MetadataEntry
	24, // 9: codegen.v1.RunPythonRequest.env_vars:type_name -> codegen.v1.RunPythonRequest.EnvVarsEntry
	25, // 10: codegen.v1.RunPythonRequest.metadata:type_name -> codegen.v1.RunPythonRequest.MetadataEntry
	26, // 11: codegen.v1.RunPythonResponse.metadata:type_name -> codegen.v1.RunPythonResponse.MetadataEntry
	27, // 12: codegen.v1.PkgInstallRequest.metadata:type_name -> codegen.v1.PkgInstallRequest.MetadataEntry
	13, // 13: codegen.v1.PkgInstallResponse.installed:type_name -> codegen.v1.PackageInfo
	28, // 14: codegen.v1.PkgInstallResponse.metadata:type_name -> codegen.v1.PkgInstallResponse.MetadataEntry
	0,  // 15: codegen.v1.ToolRequest.echo:type_name -> codegen.v1.EchoRequest
	2,  // 16: codegen.v1.ToolRequest.fs_read:type_name -> codegen.v1.FsReadRequest
	4,  // 17: codegen.v1.ToolRequest.fs_write:type_name -> codegen.v1.FsWriteRequest
	6,  // 18: codegen.v1.ToolRequest.fs_list:type_name -> codegen.v1.FsListRequest
	9,  // 19: codegen.v1.ToolRequest.run_python:type_name -> codegen.v1.RunPythonRequest
	11, // 20: codegen.v1.ToolRequest.pkg_install:type_name -> codegen.v1.PkgInstallRequest
	1,  // 21: codegen.v1.ToolResponse.echo:type_name -> codegen.v1.EchoResponse
	3,  // 22: codegen.v1.ToolResponse.fs_read:type_name -> codegen.v1.FsReadResponse
	5,  // 23: codegen.v1.ToolResponse.fs_write:type_name -> codegen.v1.FsWriteResponse
	7,  // 24: codegen.v1.ToolResponse.fs_list:type_name -> codegen.v1.FsListResponse
	10, // 25: codegen.v1.ToolResponse.run_python:type_name -> codegen.v1.RunPythonResponse
	12, // 26: codegen.v1.ToolResponse.pkg_install:type_name -> codegen.v1.PkgInstallResponse
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_api_proto_v1_tools_proto_init() }
func file_api_proto_v1_tools_proto_init() {
	if File_api_proto_v1_tools_proto != nil {
		return
	}
	file_api_proto_v1_tools_proto_msgTypes[9].OneofWrappers = []any{
		(*RunPythonRequest_Code)(nil),
		(*RunPythonRequest_File)(nil),
	}
	file_api_proto_v1_tools_proto_msgTypes[14].OneofWrappers = []any{
		(*ToolRequest_Echo)(nil),
		(*ToolRequest_FsRead)(nil),
		(*ToolRequest_FsWrite)(nil),
		(*ToolRequest_FsList)(nil),
		(*ToolRequest_RunPython)(nil),
		(*ToolRequest_PkgInstall)(nil),
	}
	file_api_proto_v1_tools_proto_msgTypes[15].OneofWrappers = []any{
		(*ToolResponse_Echo)(nil),
		(*ToolResponse_FsRead)(nil),
		(*ToolResponse_FsWrite)(nil),
		(*ToolResponse_FsList)(nil),
		(*ToolResponse_RunPython)(nil),
		(*ToolResponse_PkgInstall)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_tools_proto_rawDesc), len(file_api_proto_v1_tools_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_v1_tools_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_tools_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_tools_proto_msgTypes,
	}.Build()
	File_api_proto_v1_tools_proto = out.File
	file_api_proto_v1_tools_proto_goTypes = nil
	file_api_proto_v1_tools_proto_depIdxs = nil
}
