// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/proto/v1/worker_lifecycle.proto

package protov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerStatus_State int32

const (
	WorkerStatus_STATE_UNSPECIFIED WorkerStatus_State = 0
	WorkerStatus_STATE_IDLE        WorkerStatus_State = 1
	WorkerStatus_STATE_BUSY        WorkerStatus_State = 2
	WorkerStatus_STATE_DRAINING    WorkerStatus_State = 3
	WorkerStatus_STATE_UNHEALTHY   WorkerStatus_State = 4
)

// Enum value maps for WorkerStatus_State.
var (
	WorkerStatus_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_IDLE",
		2: "STATE_BUSY",
		3: "STATE_DRAINING",
		4: "STATE_UNHEALTHY",
	}
	WorkerStatus_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_IDLE":        1,
		"STATE_BUSY":        2,
		"STATE_DRAINING":    3,
		"STATE_UNHEALTHY":   4,
	}
)

func (x WorkerStatus_State) Enum() *WorkerStatus_State {
	p := new(WorkerStatus_State)
	*p = x
	return p
}

func (x WorkerStatus_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerStatus_State) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_worker_lifecycle_proto_enumTypes[0].Descriptor()
}

func (WorkerStatus_State) Type() protoreflect.EnumType {
	return &file_api_proto_v1_worker_lifecycle_proto_enumTypes[0]
}

func (x WorkerStatus_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerStatus_State.Descriptor instead.
func (WorkerStatus_State) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{5, 0}
}

type TaskLogEntry_Level int32

const (
	TaskLogEntry_LEVEL_UNSPECIFIED TaskLogEntry_Level = 0
	TaskLogEntry_LEVEL_DEBUG       TaskLogEntry_Level = 1
	TaskLogEntry_LEVEL_INFO        TaskLogEntry_Level = 2
	TaskLogEntry_LEVEL_WARN        TaskLogEntry_Level = 3
	TaskLogEntry_LEVEL_ERROR       TaskLogEntry_Level = 4
)

// Enum value maps for TaskLogEntry_Level.
var (
	TaskLogEntry_Level_name = map[int32]string{
		0: "LEVEL_UNSPECIFIED",
		1: "LEVEL_DEBUG",
		2: "LEVEL_INFO",
		3: "LEVEL_WARN",
		4: "LEVEL_ERROR",
	}
	TaskLogEntry_Level_value = map[string]int32{
		"LEVEL_UNSPECIFIED": 0,
		"LEVEL_DEBUG":       1,
		"LEVEL_INFO":        2,
		"LEVEL_WARN":        3,
		"LEVEL_ERROR":       4,
	}
)

func (x TaskLogEntry_Level) Enum() *TaskLogEntry_Level {
	p := new(TaskLogEntry_Level)
	*p = x
	return p
}

func (x TaskLogEntry_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskLogEntry_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_worker_lifecycle_proto_enumTypes[1].Descriptor()
}

func (TaskLogEntry_Level) Type() protoreflect.EnumType {
	return &file_api_proto_v1_worker_lifecycle_proto_enumTypes[1]
}

func (x TaskLogEntry_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskLogEntry_Level.Descriptor instead.
func (TaskLogEntry_Level) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{13, 0}
}

type TaskStreamResult_Status int32

const (
	TaskStreamResult_STATUS_UNSPECIFIED TaskStreamResult_Status = 0
	TaskStreamResult_STATUS_SUCCESS     TaskStreamResult_Status = 1
	TaskStreamResult_STATUS_FAILURE     TaskStreamResult_Status = 2
	TaskStreamResult_STATUS_TIMEOUT     TaskStreamResult_Status = 3
	TaskStreamResult_STATUS_CANCELLED   TaskStreamResult_Status = 4
)

// Enum value maps for TaskStreamResult_Status.
var (
	TaskStreamResult_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_SUCCESS",
		2: "STATUS_FAILURE",
		3: "STATUS_TIMEOUT",
		4: "STATUS_CANCELLED",
	}
	TaskStreamResult_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_SUCCESS":     1,
		"STATUS_FAILURE":     2,
		"STATUS_TIMEOUT":     3,
		"STATUS_CANCELLED":   4,
	}
)

func (x TaskStreamResult_Status) Enum() *TaskStreamResult_Status {
	p := new(TaskStreamResult_Status)
	*p = x
	return p
}

func (x TaskStreamResult_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStreamResult_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_worker_lifecycle_proto_enumTypes[2].Descriptor()
}

func (TaskStreamResult_Status) Type() protoreflect.EnumType {
	return &file_api_proto_v1_worker_lifecycle_proto_enumTypes[2]
}

func (x TaskStreamResult_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStreamResult_Status.Descriptor instead.
func (TaskStreamResult_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{14, 0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`    // Unique worker identifier (from env)
	AuthToken     string                 `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"` // Bearer token for authentication
	Capabilities  *WorkerCapabilities    `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Limits        *ResourceLimits        `protobuf:"bytes,4,opt,name=limits,proto3" json:"limits,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`                            // Worker binary version
	GrpcAddress   string                 `protobuf:"bytes,6,opt,name=grpc_address,json=grpcAddress,proto3" json:"grpc_address,omitempty"` // Worker's gRPC server address (e.g., "localhost:50051")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() *WorkerCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetGrpcAddress() string {
	if x != nil {
		return x.GrpcAddress
	}
	return ""
}

type WorkerCapabilities struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SupportedTools []string               `protobuf:"bytes,1,rep,name=supported_tools,json=supportedTools,proto3" json:"supported_tools,omitempty"`                                         // e.g., ["fs.write", "run.python"]
	Languages      []string               `protobuf:"bytes,2,rep,name=languages,proto3" json:"languages,omitempty"`                                                                         // e.g., ["python"]
	MaxSessions    int32                  `protobuf:"varint,3,opt,name=max_sessions,json=maxSessions,proto3" json:"max_sessions,omitempty"`                                                 // Max concurrent sessions this worker supports
	Metadata       map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Extensible metadata
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkerCapabilities) Reset() {
	*x = WorkerCapabilities{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerCapabilities) ProtoMessage() {}

func (x *WorkerCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerCapabilities.ProtoReflect.Descriptor instead.
func (*WorkerCapabilities) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerCapabilities) GetSupportedTools() []string {
	if x != nil {
		return x.SupportedTools
	}
	return nil
}

func (x *WorkerCapabilities) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *WorkerCapabilities) GetMaxSessions() int32 {
	if x != nil {
		return x.MaxSessions
	}
	return 0
}

func (x *WorkerCapabilities) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RegisterResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SessionId            string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`          // Worker's registration session ID
	TaskEndpoint         string                 `protobuf:"bytes,2,opt,name=task_endpoint,json=taskEndpoint,proto3" json:"task_endpoint,omitempty"` // gRPC endpoint for task assignment
	HeartbeatIntervalSec int32                  `protobuf:"varint,3,opt,name=heartbeat_interval_sec,json=heartbeatIntervalSec,proto3" json:"heartbeat_interval_sec,omitempty"`
	Accepted             bool                   `protobuf:"varint,4,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason               string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"` // If not accepted, why?
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterResponse) GetTaskEndpoint() string {
	if x != nil {
		return x.TaskEndpoint
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatIntervalSec() int32 {
	if x != nil {
		return x.HeartbeatIntervalSec
	}
	return 0
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Worker's registration session ID
	Status        *WorkerStatus          `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Capacity      *SessionCapacity       `protobuf:"bytes,4,opt,name=capacity,proto3" json:"capacity,omitempty"` // Current session availability
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() *WorkerStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *HeartbeatRequest) GetCapacity() *SessionCapacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

type SessionCapacity struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalSessions     int32                  `protobuf:"varint,1,opt,name=total_sessions,json=totalSessions,proto3" json:"total_sessions,omitempty"`             // Max sessions worker can handle
	ActiveSessions    int32                  `protobuf:"varint,2,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`          // Currently running sessions
	AvailableSessions int32                  `protobuf:"varint,3,opt,name=available_sessions,json=availableSessions,proto3" json:"available_sessions,omitempty"` // Free session slots
	Sessions          []*SessionInfo         `protobuf:"bytes,4,rep,name=sessions,proto3" json:"sessions,omitempty"`                                             // Details of active sessions
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SessionCapacity) Reset() {
	*x = SessionCapacity{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCapacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCapacity) ProtoMessage() {}

func (x *SessionCapacity) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCapacity.ProtoReflect.Descriptor instead.
func (*SessionCapacity) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{4}
}

func (x *SessionCapacity) GetTotalSessions() int32 {
	if x != nil {
		return x.TotalSessions
	}
	return 0
}

func (x *SessionCapacity) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *SessionCapacity) GetAvailableSessions() int32 {
	if x != nil {
		return x.AvailableSessions
	}
	return 0
}

func (x *SessionCapacity) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type WorkerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         WorkerStatus_State     `protobuf:"varint,1,opt,name=state,proto3,enum=codegen.v1.WorkerStatus_State" json:"state,omitempty"`
	ActiveTasks   int32                  `protobuf:"varint,2,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`   // Total tasks across all sessions
	CurrentUsage  *ResourceUsage         `protobuf:"bytes,3,opt,name=current_usage,json=currentUsage,proto3" json:"current_usage,omitempty"` // Total resource usage
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`                                 // Recent errors
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerStatus) Reset() {
	*x = WorkerStatus{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStatus) ProtoMessage() {}

func (x *WorkerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStatus.ProtoReflect.Descriptor instead.
func (*WorkerStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{5}
}

func (x *WorkerStatus) GetState() WorkerStatus_State {
	if x != nil {
		return x.State
	}
	return WorkerStatus_STATE_UNSPECIFIED
}

func (x *WorkerStatus) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

func (x *WorkerStatus) GetCurrentUsage() *ResourceUsage {
	if x != nil {
		return x.CurrentUsage
	}
	return nil
}

func (x *WorkerStatus) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContinueServing bool                   `protobuf:"varint,1,opt,name=continue_serving,json=continueServing,proto3" json:"continue_serving,omitempty"`
	Commands        []string               `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"` // e.g., ["drain", "reload_config"]
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatResponse) GetContinueServing() bool {
	if x != nil {
		return x.ContinueServing
	}
	return false
}

func (x *HeartbeatResponse) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Worker's registration session ID
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                        // Shutdown reason
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{7}
}

func (x *DeregisterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *DeregisterRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DeregisterRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{8}
}

func (x *DeregisterResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

// TaskStreamMessage is used for bidirectional task streaming
// Coordinator sends task assignments, worker sends responses
type TaskStreamMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*TaskStreamMessage_Assignment
	//	*TaskStreamMessage_Response
	//	*TaskStreamMessage_Keepalive
	//	*TaskStreamMessage_SessionCreate
	//	*TaskStreamMessage_SessionCreated
	Message       isTaskStreamMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStreamMessage) Reset() {
	*x = TaskStreamMessage{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStreamMessage) ProtoMessage() {}

func (x *TaskStreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStreamMessage.ProtoReflect.Descriptor instead.
func (*TaskStreamMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{9}
}

func (x *TaskStreamMessage) GetMessage() isTaskStreamMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *TaskStreamMessage) GetAssignment() *TaskAssignment {
	if x != nil {
		if x, ok := x.Message.(*TaskStreamMessage_Assignment); ok {
			return x.Assignment
		}
	}
	return nil
}

func (x *TaskStreamMessage) GetResponse() *TaskStreamResponse {
	if x != nil {
		if x, ok := x.Message.(*TaskStreamMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *TaskStreamMessage) GetKeepalive() *StreamKeepAlive {
	if x != nil {
		if x, ok := x.Message.(*TaskStreamMessage_Keepalive); ok {
			return x.Keepalive
		}
	}
	return nil
}

func (x *TaskStreamMessage) GetSessionCreate() *SessionCreateRequest {
	if x != nil {
		if x, ok := x.Message.(*TaskStreamMessage_SessionCreate); ok {
			return x.SessionCreate
		}
	}
	return nil
}

func (x *TaskStreamMessage) GetSessionCreated() *SessionCreateResponse {
	if x != nil {
		if x, ok := x.Message.(*TaskStreamMessage_SessionCreated); ok {
			return x.SessionCreated
		}
	}
	return nil
}

type isTaskStreamMessage_Message interface {
	isTaskStreamMessage_Message()
}

type TaskStreamMessage_Assignment struct {
	Assignment *TaskAssignment `protobuf:"bytes,1,opt,name=assignment,proto3,oneof"` // Coordinator -> Worker: execute this task
}

type TaskStreamMessage_Response struct {
	Response *TaskStreamResponse `protobuf:"bytes,2,opt,name=response,proto3,oneof"` // Worker -> Coordinator: task update/result
}

type TaskStreamMessage_Keepalive struct {
	Keepalive *StreamKeepAlive `protobuf:"bytes,3,opt,name=keepalive,proto3,oneof"` // Either direction: keep connection alive
}

type TaskStreamMessage_SessionCreate struct {
	SessionCreate *SessionCreateRequest `protobuf:"bytes,4,opt,name=session_create,json=sessionCreate,proto3,oneof"` // Coordinator -> Worker: create session
}

type TaskStreamMessage_SessionCreated struct {
	SessionCreated *SessionCreateResponse `protobuf:"bytes,5,opt,name=session_created,json=sessionCreated,proto3,oneof"` // Worker -> Coordinator: session created
}

func (*TaskStreamMessage_Assignment) isTaskStreamMessage_Message() {}

func (*TaskStreamMessage_Response) isTaskStreamMessage_Message() {}

func (*TaskStreamMessage_Keepalive) isTaskStreamMessage_Message() {}

func (*TaskStreamMessage_SessionCreate) isTaskStreamMessage_Message() {}

func (*TaskStreamMessage_SessionCreated) isTaskStreamMessage_Message() {}

// TaskAssignment is sent by coordinator to worker
// Reuses TaskContext and ExecutionConstraints from task_execution.proto
type TaskAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Arguments     map[string]string      `protobuf:"bytes,4,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Context       *TaskContext           `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`
	Constraints   *ExecutionConstraints  `protobuf:"bytes,6,opt,name=constraints,proto3" json:"constraints,omitempty"`
	Sequence      uint64                 `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"` // Monotonic sequence number for deduplication (0 = no tracking)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{10}
}

func (x *TaskAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAssignment) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TaskAssignment) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *TaskAssignment) GetArguments() map[string]string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *TaskAssignment) GetContext() *TaskContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *TaskAssignment) GetConstraints() *ExecutionConstraints {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *TaskAssignment) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// TaskStreamResponse is sent by worker to coordinator
type TaskStreamResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TaskId string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TaskStreamResponse_Progress
	//	*TaskStreamResponse_Log
	//	*TaskStreamResponse_Result
	//	*TaskStreamResponse_Error
	Payload       isTaskStreamResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStreamResponse) Reset() {
	*x = TaskStreamResponse{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStreamResponse) ProtoMessage() {}

func (x *TaskStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStreamResponse.ProtoReflect.Descriptor instead.
func (*TaskStreamResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{11}
}

func (x *TaskStreamResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStreamResponse) GetPayload() isTaskStreamResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TaskStreamResponse) GetProgress() *TaskProgressUpdate {
	if x != nil {
		if x, ok := x.Payload.(*TaskStreamResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *TaskStreamResponse) GetLog() *TaskLogEntry {
	if x != nil {
		if x, ok := x.Payload.(*TaskStreamResponse_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *TaskStreamResponse) GetResult() *TaskStreamResult {
	if x != nil {
		if x, ok := x.Payload.(*TaskStreamResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *TaskStreamResponse) GetError() *TaskStreamError {
	if x != nil {
		if x, ok := x.Payload.(*TaskStreamResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isTaskStreamResponse_Payload interface {
	isTaskStreamResponse_Payload()
}

type TaskStreamResponse_Progress struct {
	Progress *TaskProgressUpdate `protobuf:"bytes,2,opt,name=progress,proto3,oneof"`
}

type TaskStreamResponse_Log struct {
	Log *TaskLogEntry `protobuf:"bytes,3,opt,name=log,proto3,oneof"`
}

type TaskStreamResponse_Result struct {
	Result *TaskStreamResult `protobuf:"bytes,4,opt,name=result,proto3,oneof"`
}

type TaskStreamResponse_Error struct {
	Error *TaskStreamError `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

func (*TaskStreamResponse_Progress) isTaskStreamResponse_Payload() {}

func (*TaskStreamResponse_Log) isTaskStreamResponse_Payload() {}

func (*TaskStreamResponse_Result) isTaskStreamResponse_Payload() {}

func (*TaskStreamResponse_Error) isTaskStreamResponse_Payload() {}

type TaskProgressUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PercentComplete int32                  `protobuf:"varint,1,opt,name=percent_complete,json=percentComplete,proto3" json:"percent_complete,omitempty"`
	Stage           string                 `protobuf:"bytes,2,opt,name=stage,proto3" json:"stage,omitempty"`
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskProgressUpdate) Reset() {
	*x = TaskProgressUpdate{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskProgressUpdate) ProtoMessage() {}

func (x *TaskProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskProgressUpdate.ProtoReflect.Descriptor instead.
func (*TaskProgressUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{12}
}

func (x *TaskProgressUpdate) GetPercentComplete() int32 {
	if x != nil {
		return x.PercentComplete
	}
	return 0
}

func (x *TaskProgressUpdate) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *TaskProgressUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TaskLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         TaskLogEntry_Level     `protobuf:"varint,1,opt,name=level,proto3,enum=codegen.v1.TaskLogEntry_Level" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLogEntry) Reset() {
	*x = TaskLogEntry{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLogEntry) ProtoMessage() {}

func (x *TaskLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLogEntry.ProtoReflect.Descriptor instead.
func (*TaskLogEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{13}
}

func (x *TaskLogEntry) GetLevel() TaskLogEntry_Level {
	if x != nil {
		return x.Level
	}
	return TaskLogEntry_LEVEL_UNSPECIFIED
}

func (x *TaskLogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskLogEntry) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *TaskLogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type TaskStreamResult struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Status          TaskStreamResult_Status `protobuf:"varint,1,opt,name=status,proto3,enum=codegen.v1.TaskStreamResult_Status" json:"status,omitempty"`
	Outputs         map[string]string       `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Artifacts       []string                `protobuf:"bytes,3,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	Metadata        *TaskExecutionMetadata  `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Sequence        uint64                  `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`                                                                                                               // Sequence number of completed task (for deduplication tracking)
	SessionMetadata map[string]string       `protobuf:"bytes,6,rep,name=session_metadata,json=sessionMetadata,proto3" json:"session_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Updated session metadata after task execution (worker is master)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskStreamResult) Reset() {
	*x = TaskStreamResult{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStreamResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStreamResult) ProtoMessage() {}

func (x *TaskStreamResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStreamResult.ProtoReflect.Descriptor instead.
func (*TaskStreamResult) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{14}
}

func (x *TaskStreamResult) GetStatus() TaskStreamResult_Status {
	if x != nil {
		return x.Status
	}
	return TaskStreamResult_STATUS_UNSPECIFIED
}

func (x *TaskStreamResult) GetOutputs() map[string]string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *TaskStreamResult) GetArtifacts() []string {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *TaskStreamResult) GetMetadata() *TaskExecutionMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TaskStreamResult) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *TaskStreamResult) GetSessionMetadata() map[string]string {
	if x != nil {
		return x.SessionMetadata
	}
	return nil
}

type TaskExecutionMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTimeMs   int64                  `protobuf:"varint,1,opt,name=start_time_ms,json=startTimeMs,proto3" json:"start_time_ms,omitempty"`
	EndTimeMs     int64                  `protobuf:"varint,2,opt,name=end_time_ms,json=endTimeMs,proto3" json:"end_time_ms,omitempty"`
	DurationMs    int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	PeakUsage     *ResourceUsage         `protobuf:"bytes,4,opt,name=peak_usage,json=peakUsage,proto3" json:"peak_usage,omitempty"`
	ExitCode      int32                  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskExecutionMetadata) Reset() {
	*x = TaskExecutionMetadata{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecutionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecutionMetadata) ProtoMessage() {}

func (x *TaskExecutionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecutionMetadata.ProtoReflect.Descriptor instead.
func (*TaskExecutionMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{15}
}

func (x *TaskExecutionMetadata) GetStartTimeMs() int64 {
	if x != nil {
		return x.StartTimeMs
	}
	return 0
}

func (x *TaskExecutionMetadata) GetEndTimeMs() int64 {
	if x != nil {
		return x.EndTimeMs
	}
	return 0
}

func (x *TaskExecutionMetadata) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TaskExecutionMetadata) GetPeakUsage() *ResourceUsage {
	if x != nil {
		return x.PeakUsage
	}
	return nil
}

func (x *TaskExecutionMetadata) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type TaskStreamError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	Retriable     bool                   `protobuf:"varint,4,opt,name=retriable,proto3" json:"retriable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStreamError) Reset() {
	*x = TaskStreamError{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStreamError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStreamError) ProtoMessage() {}

func (x *TaskStreamError) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStreamError.ProtoReflect.Descriptor instead.
func (*TaskStreamError) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{16}
}

func (x *TaskStreamError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TaskStreamError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskStreamError) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *TaskStreamError) GetRetriable() bool {
	if x != nil {
		return x.Retriable
	}
	return false
}

type StreamKeepAlive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamKeepAlive) Reset() {
	*x = StreamKeepAlive{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamKeepAlive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamKeepAlive) ProtoMessage() {}

func (x *StreamKeepAlive) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamKeepAlive.ProtoReflect.Descriptor instead.
func (*StreamKeepAlive) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{17}
}

func (x *StreamKeepAlive) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

// SessionCreateRequest is sent by coordinator to worker to create a new session
type SessionCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                                                     // Session ID to create
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`                                                               // Workspace identifier
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                                              // User/tenant identifier
	EnvVars       map[string]string      `protobuf:"bytes,4,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Environment variables for session
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`              // Initial session metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionCreateRequest) Reset() {
	*x = SessionCreateRequest{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCreateRequest) ProtoMessage() {}

func (x *SessionCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCreateRequest.ProtoReflect.Descriptor instead.
func (*SessionCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{18}
}

func (x *SessionCreateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionCreateRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *SessionCreateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionCreateRequest) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *SessionCreateRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// SessionCreateResponse is sent by worker to coordinator after session creation
type SessionCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                                        // Session ID that was created
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`                                                                            // Whether creation succeeded
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                                                                                 // Error message if failed
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Initial session metadata from worker
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionCreateResponse) Reset() {
	*x = SessionCreateResponse{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCreateResponse) ProtoMessage() {}

func (x *SessionCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCreateResponse.ProtoReflect.Descriptor instead.
func (*SessionCreateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{19}
}

func (x *SessionCreateResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionCreateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SessionCreateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SessionCreateResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_api_proto_v1_worker_lifecycle_proto protoreflect.FileDescriptor

const file_api_proto_v1_worker_lifecycle_proto_rawDesc = "" +
	"\n" +
	"#api/proto/v1/worker_lifecycle.proto\x12\n" +
	"codegen.v1\x1a\x19api/proto/v1/common.proto\x1a!api/proto/v1/task_execution.proto\"\x82\x02\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\x12B\n" +
	"\fcapabilities\x18\x03 \x01(\v2\x1e.codegen.v1.WorkerCapabilitiesR\fcapabilities\x122\n" +
	"\x06limits\x18\x04 \x01(\v2\x1a.codegen.v1.ResourceLimitsR\x06limits\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12!\n" +
	"\fgrpc_address\x18\x06 \x01(\tR\vgrpcAddress\"\x85\x02\n" +
	"\x12WorkerCapabilities\x12'\n" +
	"\x0fsupported_tools\x18\x01 \x03(\tR\x0esupportedTools\x12\x1c\n" +
	"\tlanguages\x18\x02 \x03(\tR\tlanguages\x12!\n" +
	"\fmax_sessions\x18\x03 \x01(\x05R\vmaxSessions\x12H\n" +
	"\bmetadata\x18\x04 \x03(\v2,.codegen.v1.WorkerCapabilities.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc0\x01\n" +
	"\x10RegisterResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rtask_endpoint\x18\x02 \x01(\tR\ftaskEndpoint\x124\n" +
	"\x16heartbeat_interval_sec\x18\x03 \x01(\x05R\x14heartbeatIntervalSec\x12\x1a\n" +
	"\baccepted\x18\x04 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\xb9\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x120\n" +
	"\x06status\x18\x03 \x01(\v2\x18.codegen.v1.WorkerStatusR\x06status\x127\n" +
	"\bcapacity\x18\x04 \x01(\v2\x1b.codegen.v1.SessionCapacityR\bcapacity\"\xc5\x01\n" +
	"\x0fSessionCapacity\x12%\n" +
	"\x0etotal_sessions\x18\x01 \x01(\x05R\rtotalSessions\x12'\n" +
	"\x0factive_sessions\x18\x02 \x01(\x05R\x0eactiveSessions\x12-\n" +
	"\x12available_sessions\x18\x03 \x01(\x05R\x11availableSessions\x123\n" +
	"\bsessions\x18\x04 \x03(\v2\x17.codegen.v1.SessionInfoR\bsessions\"\xa8\x02\n" +
	"\fWorkerStatus\x124\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1e.codegen.v1.WorkerStatus.StateR\x05state\x12!\n" +
	"\factive_tasks\x18\x02 \x01(\x05R\vactiveTasks\x12>\n" +
	"\rcurrent_usage\x18\x03 \x01(\v2\x19.codegen.v1.ResourceUsageR\fcurrentUsage\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\"g\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"STATE_IDLE\x10\x01\x12\x0e\n" +
	"\n" +
	"STATE_BUSY\x10\x02\x12\x12\n" +
	"\x0eSTATE_DRAINING\x10\x03\x12\x13\n" +
	"\x0fSTATE_UNHEALTHY\x10\x04\"Z\n" +
	"\x11HeartbeatResponse\x12)\n" +
	"\x10continue_serving\x18\x01 \x01(\bR\x0fcontinueServing\x12\x1a\n" +
	"\bcommands\x18\x02 \x03(\tR\bcommands\"g\n" +
	"\x11DeregisterRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"8\n" +
	"\x12DeregisterResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"\xf0\x02\n" +
	"\x11TaskStreamMessage\x12<\n" +
	"\n" +
	"assignment\x18\x01 \x01(\v2\x1a.codegen.v1.TaskAssignmentH\x00R\n" +
	"assignment\x12<\n" +
	"\bresponse\x18\x02 \x01(\v2\x1e.codegen.v1.TaskStreamResponseH\x00R\bresponse\x12;\n" +
	"\tkeepalive\x18\x03 \x01(\v2\x1b.codegen.v1.StreamKeepAliveH\x00R\tkeepalive\x12I\n" +
	"\x0esession_create\x18\x04 \x01(\v2 .codegen.v1.SessionCreateRequestH\x00R\rsessionCreate\x12L\n" +
	"\x0fsession_created\x18\x05 \x01(\v2!.codegen.v1.SessionCreateResponseH\x00R\x0esessionCreatedB\t\n" +
	"\amessage\"\xff\x02\n" +
	"\x0eTaskAssignment\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12G\n" +
	"\targuments\x18\x04 \x03(\v2).codegen.v1.TaskAssignment.ArgumentsEntryR\targuments\x121\n" +
	"\acontext\x18\x05 \x01(\v2\x17.codegen.v1.TaskContextR\acontext\x12B\n" +
	"\vconstraints\x18\x06 \x01(\v2 .codegen.v1.ExecutionConstraintsR\vconstraints\x12\x1a\n" +
	"\bsequence\x18\a \x01(\x04R\bsequence\x1a<\n" +
	"\x0eArgumentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x91\x02\n" +
	"\x12TaskStreamResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12<\n" +
	"\bprogress\x18\x02 \x01(\v2\x1e.codegen.v1.TaskProgressUpdateH\x00R\bprogress\x12,\n" +
	"\x03log\x18\x03 \x01(\v2\x18.codegen.v1.TaskLogEntryH\x00R\x03log\x126\n" +
	"\x06result\x18\x04 \x01(\v2\x1c.codegen.v1.TaskStreamResultH\x00R\x06result\x123\n" +
	"\x05error\x18\x05 \x01(\v2\x1b.codegen.v1.TaskStreamErrorH\x00R\x05errorB\t\n" +
	"\apayload\"o\n" +
	"\x12TaskProgressUpdate\x12)\n" +
	"\x10percent_complete\x18\x01 \x01(\x05R\x0fpercentComplete\x12\x14\n" +
	"\x05stage\x18\x02 \x01(\tR\x05stage\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xfb\x01\n" +
	"\fTaskLogEntry\x124\n" +
	"\x05level\x18\x01 \x01(\x0e2\x1e.codegen.v1.TaskLogEntry.LevelR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"`\n" +
	"\x05Level\x12\x15\n" +
	"\x11LEVEL_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vLEVEL_DEBUG\x10\x01\x12\x0e\n" +
	"\n" +
	"LEVEL_INFO\x10\x02\x12\x0e\n" +
	"\n" +
	"LEVEL_WARN\x10\x03\x12\x0f\n" +
	"\vLEVEL_ERROR\x10\x04\"\xdf\x04\n" +
	"\x10TaskStreamResult\x12;\n" +
	"\x06status\x18\x01 \x01(\x0e2#.codegen.v1.TaskStreamResult.StatusR\x06status\x12C\n" +
	"\aoutputs\x18\x02 \x03(\v2).codegen.v1.TaskStreamResult.OutputsEntryR\aoutputs\x12\x1c\n" +
	"\tartifacts\x18\x03 \x03(\tR\tartifacts\x12=\n" +
	"\bmetadata\x18\x04 \x01(\v2!.codegen.v1.TaskExecutionMetadataR\bmetadata\x12\x1a\n" +
	"\bsequence\x18\x05 \x01(\x04R\bsequence\x12\\\n" +
	"\x10session_metadata\x18\x06 \x03(\v21.codegen.v1.TaskStreamResult.SessionMetadataEntryR\x0fsessionMetadata\x1a:\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14SessionMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_SUCCESS\x10\x01\x12\x12\n" +
	"\x0eSTATUS_FAILURE\x10\x02\x12\x12\n" +
	"\x0eSTATUS_TIMEOUT\x10\x03\x12\x14\n" +
	"\x10STATUS_CANCELLED\x10\x04\"\xd3\x01\n" +
	"\x15TaskExecutionMetadata\x12\"\n" +
	"\rstart_time_ms\x18\x01 \x01(\x03R\vstartTimeMs\x12\x1e\n" +
	"\vend_time_ms\x18\x02 \x01(\x03R\tendTimeMs\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\x128\n" +
	"\n" +
	"peak_usage\x18\x04 \x01(\v2\x19.codegen.v1.ResourceUsageR\tpeakUsage\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\"w\n" +
	"\x0fTaskStreamError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\x12\x1c\n" +
	"\tretriable\x18\x04 \x01(\bR\tretriable\"4\n" +
	"\x0fStreamKeepAlive\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\"\x80\x03\n" +
	"\x14SessionCreateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12H\n" +
	"\benv_vars\x18\x04 \x03(\v2-.codegen.v1.SessionCreateRequest.EnvVarsEntryR\aenvVars\x12J\n" +
	"\bmetadata\x18\x05 \x03(\v2..codegen.v1.SessionCreateRequest.MetadataEntryR\bmetadata\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf0\x01\n" +
	"\x15SessionCreateResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12K\n" +
	"\bmetadata\x18\x04 \x03(\v2/.codegen.v1.SessionCreateResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xcb\x02\n" +
	"\x0fWorkerLifecycle\x12K\n" +
	"\x0eRegisterWorker\x12\x1b.codegen.v1.RegisterRequest\x1a\x1c.codegen.v1.RegisterResponse\x12H\n" +
	"\tHeartbeat\x12\x1c.codegen.v1.HeartbeatRequest\x1a\x1d.codegen.v1.HeartbeatResponse\x12Q\n" +
	"\x10DeregisterWorker\x12\x1d.codegen.v1.DeregisterRequest\x1a\x1e.codegen.v1.DeregisterResponse\x12N\n" +
	"\n" +
	"TaskStream\x12\x1d.codegen.v1.TaskStreamMessage\x1a\x1d.codegen.v1.TaskStreamMessage(\x010\x01B9Z7github.com/altairalabs/codegen-mcp/api/proto/v1;protov1b\x06proto3"

var (
	file_api_proto_v1_worker_lifecycle_proto_rawDescOnce sync.Once
	file_api_proto_v1_worker_lifecycle_proto_rawDescData []byte
)

func file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP() []byte {
	file_api_proto_v1_worker_lifecycle_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_worker_lifecycle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_worker_lifecycle_proto_rawDesc), len(file_api_proto_v1_worker_lifecycle_proto_rawDesc)))
	})
	return file_api_proto_v1_worker_lifecycle_proto_rawDescData
}

var file_api_proto_v1_worker_lifecycle_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_proto_v1_worker_lifecycle_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_api_proto_v1_worker_lifecycle_proto_goTypes = []any{
	(WorkerStatus_State)(0),       // 0: codegen.v1.WorkerStatus.State
	(TaskLogEntry_Level)(0),       // 1: codegen.v1.TaskLogEntry.Level
	(TaskStreamResult_Status)(0),  // 2: codegen.v1.TaskStreamResult.Status
	(*RegisterRequest)(nil),       // 3: codegen.v1.RegisterRequest
	(*WorkerCapabilities)(nil),    // 4: codegen.v1.WorkerCapabilities
	(*RegisterResponse)(nil),      // 5: codegen.v1.RegisterResponse
	(*HeartbeatRequest)(nil),      // 6: codegen.v1.HeartbeatRequest
	(*SessionCapacity)(nil),       // 7: codegen.v1.SessionCapacity
	(*WorkerStatus)(nil),          // 8: codegen.v1.WorkerStatus
	(*HeartbeatResponse)(nil),     // 9: codegen.v1.HeartbeatResponse
	(*DeregisterRequest)(nil),     // 10: codegen.v1.DeregisterRequest
	(*DeregisterResponse)(nil),    // 11: codegen.v1.DeregisterResponse
	(*TaskStreamMessage)(nil),     // 12: codegen.v1.TaskStreamMessage
	(*TaskAssignment)(nil),        // 13: codegen.v1.TaskAssignment
	(*TaskStreamResponse)(nil),    // 14: codegen.v1.TaskStreamResponse
	(*TaskProgressUpdate)(nil),    // 15: codegen.v1.TaskProgressUpdate
	(*TaskLogEntry)(nil),          // 16: codegen.v1.TaskLogEntry
	(*TaskStreamResult)(nil),      // 17: codegen.v1.TaskStreamResult
	(*TaskExecutionMetadata)(nil), // 18: codegen.v1.TaskExecutionMetadata
	(*TaskStreamError)(nil),       // 19: codegen.v1.TaskStreamError
	(*StreamKeepAlive)(nil),       // 20: codegen.v1.StreamKeepAlive
	(*SessionCreateRequest)(nil),  // 21: codegen.v1.SessionCreateRequest
	(*SessionCreateResponse)(nil), // 22: codegen.v1.SessionCreateResponse
	nil,                           // 23: codegen.v1.WorkerCapabilities.MetadataEntry
	nil,                           // 24: codegen.v1.TaskAssignment.ArgumentsEntry
	nil,                           // 25: codegen.v1.TaskStreamResult.OutputsEntry
	nil,                           // 26: codegen.v1.TaskStreamResult.SessionMetadataEntry
	nil,                           // 27: codegen.v1.SessionCreateRequest.EnvVarsEntry
	nil,                           // 28: codegen.v1.SessionCreateRequest.MetadataEntry
	nil,                           // 29: codegen.v1.SessionCreateResponse.MetadataEntry
	(*ResourceLimits)(nil),        // 30: codegen.v1.ResourceLimits
	(*SessionInfo)(nil),           // 31: codegen.v1.SessionInfo
	(*ResourceUsage)(nil),         // 32: codegen.v1.ResourceUsage
	(*TaskContext)(nil),           // 33: codegen.v1.TaskContext
	(*ExecutionConstraints)(nil),  // 34: codegen.v1.ExecutionConstraints
}
var file_api_proto_v1_worker_lifecycle_proto_depIdxs = []int32{
	4,  // 0: codegen.v1.RegisterRequest.capabilities:type_name -> codegen.v1.WorkerCapabilities
	30, // 1: codegen.v1.RegisterRequest.limits:type_name -> codegen.v1.ResourceLimits
	23, // 2: codegen.v1.WorkerCapabilities.metadata:type_name -> codegen.v1.WorkerCapabilities.MetadataEntry
	8,  // 3: codegen.v1.HeartbeatRequest.status:type_name -> codegen.v1.WorkerStatus
	7,  // 4: codegen.v1.HeartbeatRequest.capacity:type_name -> codegen.v1.SessionCapacity
	31, // 5: codegen.v1.SessionCapacity.sessions:type_name -> codegen.v1.SessionInfo
	0,  // 6: codegen.v1.WorkerStatus.state:type_name -> codegen.v1.WorkerStatus.State
	32, // 7: codegen.v1.WorkerStatus.current_usage:type_name -> codegen.v1.ResourceUsage
	13, // 8: codegen.v1.TaskStreamMessage.assignment:type_name -> codegen.v1.TaskAssignment
	14, // 9: codegen.v1.TaskStreamMessage.response:type_name -> codegen.v1.TaskStreamResponse
	20, // 10: codegen.v1.TaskStreamMessage.keepalive:type_name -> codegen.v1.StreamKeepAlive
	21, // 11: codegen.v1.TaskStreamMessage.session_create:type_name -> codegen.v1.SessionCreateRequest
	22, // 12: codegen.v1.TaskStreamMessage.session_created:type_name -> codegen.v1.SessionCreateResponse
	24, // 13: codegen.v1.TaskAssignment.arguments:type_name -> codegen.v1.TaskAssignment.ArgumentsEntry
	33, // 14: codegen.v1.TaskAssignment.context:type_name -> codegen.v1.TaskContext
	34, // 15: codegen.v1.TaskAssignment.constraints:type_name -> codegen.v1.ExecutionConstraints
	15, // 16: codegen.v1.TaskStreamResponse.progress:type_name -> codegen.v1.TaskProgressUpdate
	16, // 17: codegen.v1.TaskStreamResponse.log:type_name -> codegen.v1.TaskLogEntry
	17, // 18: codegen.v1.TaskStreamResponse.result:type_name -> codegen.v1.TaskStreamResult
	19, // 19: codegen.v1.TaskStreamResponse.error:type_name -> codegen.v1.TaskStreamError
	1,  // 20: codegen.v1.TaskLogEntry.level:type_name -> codegen.v1.TaskLogEntry.Level
	2,  // 21: codegen.v1.TaskStreamResult.status:type_name -> codegen.v1.TaskStreamResult.Status
	25, // 22: codegen.v1.TaskStreamResult.outputs:type_name -> codegen.v1.TaskStreamResult.OutputsEntry
	18, // 23: codegen.v1.TaskStreamResult.metadata:type_name -> codegen.v1.TaskExecutionMetadata
	26, // 24: codegen.v1.TaskStreamResult.session_metadata:type_name -> codegen.v1.TaskStreamResult.SessionMetadataEntry
	32, // 25: codegen.v1.TaskExecutionMetadata.peak_usage:type_name -> codegen.v1.ResourceUsage
	27, // 26: codegen.v1.SessionCreateRequest.env_vars:type_name -> codegen.v1.SessionCreateRequest.EnvVarsEntry
	28, // 27: codegen.v1.SessionCreateRequest.metadata:type_name -> codegen.v1.SessionCreateRequest.MetadataEntry
	29, // 28: codegen.v1.SessionCreateResponse.metadata:type_name -> codegen.v1.SessionCreateResponse.MetadataEntry
	3,  // 29: codegen.v1.WorkerLifecycle.RegisterWorker:input_type -> codegen.v1.RegisterRequest
	6,  // 30: codegen.v1.WorkerLifecycle.Heartbeat:input_type -> codegen.v1.HeartbeatRequest
	10, // 31: codegen.v1.WorkerLifecycle.DeregisterWorker:input_type -> codegen.v1.DeregisterRequest
	12, // 32: codegen.v1.WorkerLifecycle.TaskStream:input_type -> codegen.v1.TaskStreamMessage
	5,  // 33: codegen.v1.WorkerLifecycle.RegisterWorker:output_type -> codegen.v1.RegisterResponse
	9,  // 34: codegen.v1.WorkerLifecycle.Heartbeat:output_type -> codegen.v1.HeartbeatResponse
	11, // 35: codegen.v1.WorkerLifecycle.DeregisterWorker:output_type -> codegen.v1.DeregisterResponse
	12, // 36: codegen.v1.WorkerLifecycle.TaskStream:output_type -> codegen.v1.TaskStreamMessage
	33, // [33:37] is the sub-list for method output_type
	29, // [29:33] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_api_proto_v1_worker_lifecycle_proto_init() }
func file_api_proto_v1_worker_lifecycle_proto_init() {
	if File_api_proto_v1_worker_lifecycle_proto != nil {
		return
	}
	file_api_proto_v1_common_proto_init()
	file_api_proto_v1_task_execution_proto_init()
	file_api_proto_v1_worker_lifecycle_proto_msgTypes[9].OneofWrappers = []any{
		(*TaskStreamMessage_Assignment)(nil),
		(*TaskStreamMessage_Response)(nil),
		(*TaskStreamMessage_Keepalive)(nil),
		(*TaskStreamMessage_SessionCreate)(nil),
		(*TaskStreamMessage_SessionCreated)(nil),
	}
	file_api_proto_v1_worker_lifecycle_proto_msgTypes[11].OneofWrappers = []any{
		(*TaskStreamResponse_Progress)(nil),
		(*TaskStreamResponse_Log)(nil),
		(*TaskStreamResponse_Result)(nil),
		(*TaskStreamResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_worker_lifecycle_proto_rawDesc), len(file_api_proto_v1_worker_lifecycle_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_worker_lifecycle_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_worker_lifecycle_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_worker_lifecycle_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_worker_lifecycle_proto_msgTypes,
	}.Build()
	File_api_proto_v1_worker_lifecycle_proto = out.File
	file_api_proto_v1_worker_lifecycle_proto_goTypes = nil
	file_api_proto_v1_worker_lifecycle_proto_depIdxs = nil
}
