// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/proto/v1/worker_lifecycle.proto

package protov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerStatus_State int32

const (
	WorkerStatus_STATE_UNSPECIFIED WorkerStatus_State = 0
	WorkerStatus_STATE_IDLE        WorkerStatus_State = 1
	WorkerStatus_STATE_BUSY        WorkerStatus_State = 2
	WorkerStatus_STATE_DRAINING    WorkerStatus_State = 3
	WorkerStatus_STATE_UNHEALTHY   WorkerStatus_State = 4
)

// Enum value maps for WorkerStatus_State.
var (
	WorkerStatus_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_IDLE",
		2: "STATE_BUSY",
		3: "STATE_DRAINING",
		4: "STATE_UNHEALTHY",
	}
	WorkerStatus_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_IDLE":        1,
		"STATE_BUSY":        2,
		"STATE_DRAINING":    3,
		"STATE_UNHEALTHY":   4,
	}
)

func (x WorkerStatus_State) Enum() *WorkerStatus_State {
	p := new(WorkerStatus_State)
	*p = x
	return p
}

func (x WorkerStatus_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerStatus_State) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_worker_lifecycle_proto_enumTypes[0].Descriptor()
}

func (WorkerStatus_State) Type() protoreflect.EnumType {
	return &file_api_proto_v1_worker_lifecycle_proto_enumTypes[0]
}

func (x WorkerStatus_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerStatus_State.Descriptor instead.
func (WorkerStatus_State) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{5, 0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`    // Unique worker identifier (from env)
	AuthToken     string                 `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"` // Bearer token for authentication
	Capabilities  *WorkerCapabilities    `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Limits        *ResourceLimits        `protobuf:"bytes,4,opt,name=limits,proto3" json:"limits,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"` // Worker binary version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() *WorkerCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type WorkerCapabilities struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SupportedTools []string               `protobuf:"bytes,1,rep,name=supported_tools,json=supportedTools,proto3" json:"supported_tools,omitempty"`                                         // e.g., ["fs.write", "run.python"]
	Languages      []string               `protobuf:"bytes,2,rep,name=languages,proto3" json:"languages,omitempty"`                                                                         // e.g., ["python"]
	MaxSessions    int32                  `protobuf:"varint,3,opt,name=max_sessions,json=maxSessions,proto3" json:"max_sessions,omitempty"`                                                 // Max concurrent sessions this worker supports
	Metadata       map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Extensible metadata
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkerCapabilities) Reset() {
	*x = WorkerCapabilities{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerCapabilities) ProtoMessage() {}

func (x *WorkerCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerCapabilities.ProtoReflect.Descriptor instead.
func (*WorkerCapabilities) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerCapabilities) GetSupportedTools() []string {
	if x != nil {
		return x.SupportedTools
	}
	return nil
}

func (x *WorkerCapabilities) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *WorkerCapabilities) GetMaxSessions() int32 {
	if x != nil {
		return x.MaxSessions
	}
	return 0
}

func (x *WorkerCapabilities) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RegisterResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SessionId            string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`          // Worker's registration session ID
	TaskEndpoint         string                 `protobuf:"bytes,2,opt,name=task_endpoint,json=taskEndpoint,proto3" json:"task_endpoint,omitempty"` // gRPC endpoint for task assignment
	HeartbeatIntervalSec int32                  `protobuf:"varint,3,opt,name=heartbeat_interval_sec,json=heartbeatIntervalSec,proto3" json:"heartbeat_interval_sec,omitempty"`
	Accepted             bool                   `protobuf:"varint,4,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason               string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"` // If not accepted, why?
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterResponse) GetTaskEndpoint() string {
	if x != nil {
		return x.TaskEndpoint
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatIntervalSec() int32 {
	if x != nil {
		return x.HeartbeatIntervalSec
	}
	return 0
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Worker's registration session ID
	Status        *WorkerStatus          `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Capacity      *SessionCapacity       `protobuf:"bytes,4,opt,name=capacity,proto3" json:"capacity,omitempty"` // Current session availability
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() *WorkerStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *HeartbeatRequest) GetCapacity() *SessionCapacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

type SessionCapacity struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalSessions     int32                  `protobuf:"varint,1,opt,name=total_sessions,json=totalSessions,proto3" json:"total_sessions,omitempty"`             // Max sessions worker can handle
	ActiveSessions    int32                  `protobuf:"varint,2,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`          // Currently running sessions
	AvailableSessions int32                  `protobuf:"varint,3,opt,name=available_sessions,json=availableSessions,proto3" json:"available_sessions,omitempty"` // Free session slots
	Sessions          []*SessionInfo         `protobuf:"bytes,4,rep,name=sessions,proto3" json:"sessions,omitempty"`                                             // Details of active sessions
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SessionCapacity) Reset() {
	*x = SessionCapacity{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCapacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCapacity) ProtoMessage() {}

func (x *SessionCapacity) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCapacity.ProtoReflect.Descriptor instead.
func (*SessionCapacity) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{4}
}

func (x *SessionCapacity) GetTotalSessions() int32 {
	if x != nil {
		return x.TotalSessions
	}
	return 0
}

func (x *SessionCapacity) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *SessionCapacity) GetAvailableSessions() int32 {
	if x != nil {
		return x.AvailableSessions
	}
	return 0
}

func (x *SessionCapacity) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type WorkerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         WorkerStatus_State     `protobuf:"varint,1,opt,name=state,proto3,enum=codegen.v1.WorkerStatus_State" json:"state,omitempty"`
	ActiveTasks   int32                  `protobuf:"varint,2,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`   // Total tasks across all sessions
	CurrentUsage  *ResourceUsage         `protobuf:"bytes,3,opt,name=current_usage,json=currentUsage,proto3" json:"current_usage,omitempty"` // Total resource usage
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`                                 // Recent errors
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerStatus) Reset() {
	*x = WorkerStatus{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStatus) ProtoMessage() {}

func (x *WorkerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStatus.ProtoReflect.Descriptor instead.
func (*WorkerStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{5}
}

func (x *WorkerStatus) GetState() WorkerStatus_State {
	if x != nil {
		return x.State
	}
	return WorkerStatus_STATE_UNSPECIFIED
}

func (x *WorkerStatus) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

func (x *WorkerStatus) GetCurrentUsage() *ResourceUsage {
	if x != nil {
		return x.CurrentUsage
	}
	return nil
}

func (x *WorkerStatus) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContinueServing bool                   `protobuf:"varint,1,opt,name=continue_serving,json=continueServing,proto3" json:"continue_serving,omitempty"`
	Commands        []string               `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"` // e.g., ["drain", "reload_config"]
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatResponse) GetContinueServing() bool {
	if x != nil {
		return x.ContinueServing
	}
	return false
}

func (x *HeartbeatResponse) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Worker's registration session ID
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                        // Shutdown reason
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{7}
}

func (x *DeregisterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *DeregisterRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DeregisterRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_lifecycle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP(), []int{8}
}

func (x *DeregisterResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_api_proto_v1_worker_lifecycle_proto protoreflect.FileDescriptor

const file_api_proto_v1_worker_lifecycle_proto_rawDesc = "" +
	"\n" +
	"#api/proto/v1/worker_lifecycle.proto\x12\n" +
	"codegen.v1\x1a\x19api/proto/v1/common.proto\"\xdf\x01\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\x12B\n" +
	"\fcapabilities\x18\x03 \x01(\v2\x1e.codegen.v1.WorkerCapabilitiesR\fcapabilities\x122\n" +
	"\x06limits\x18\x04 \x01(\v2\x1a.codegen.v1.ResourceLimitsR\x06limits\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\"\x85\x02\n" +
	"\x12WorkerCapabilities\x12'\n" +
	"\x0fsupported_tools\x18\x01 \x03(\tR\x0esupportedTools\x12\x1c\n" +
	"\tlanguages\x18\x02 \x03(\tR\tlanguages\x12!\n" +
	"\fmax_sessions\x18\x03 \x01(\x05R\vmaxSessions\x12H\n" +
	"\bmetadata\x18\x04 \x03(\v2,.codegen.v1.WorkerCapabilities.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc0\x01\n" +
	"\x10RegisterResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rtask_endpoint\x18\x02 \x01(\tR\ftaskEndpoint\x124\n" +
	"\x16heartbeat_interval_sec\x18\x03 \x01(\x05R\x14heartbeatIntervalSec\x12\x1a\n" +
	"\baccepted\x18\x04 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\xb9\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x120\n" +
	"\x06status\x18\x03 \x01(\v2\x18.codegen.v1.WorkerStatusR\x06status\x127\n" +
	"\bcapacity\x18\x04 \x01(\v2\x1b.codegen.v1.SessionCapacityR\bcapacity\"\xc5\x01\n" +
	"\x0fSessionCapacity\x12%\n" +
	"\x0etotal_sessions\x18\x01 \x01(\x05R\rtotalSessions\x12'\n" +
	"\x0factive_sessions\x18\x02 \x01(\x05R\x0eactiveSessions\x12-\n" +
	"\x12available_sessions\x18\x03 \x01(\x05R\x11availableSessions\x123\n" +
	"\bsessions\x18\x04 \x03(\v2\x17.codegen.v1.SessionInfoR\bsessions\"\xa8\x02\n" +
	"\fWorkerStatus\x124\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1e.codegen.v1.WorkerStatus.StateR\x05state\x12!\n" +
	"\factive_tasks\x18\x02 \x01(\x05R\vactiveTasks\x12>\n" +
	"\rcurrent_usage\x18\x03 \x01(\v2\x19.codegen.v1.ResourceUsageR\fcurrentUsage\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\"g\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"STATE_IDLE\x10\x01\x12\x0e\n" +
	"\n" +
	"STATE_BUSY\x10\x02\x12\x12\n" +
	"\x0eSTATE_DRAINING\x10\x03\x12\x13\n" +
	"\x0fSTATE_UNHEALTHY\x10\x04\"Z\n" +
	"\x11HeartbeatResponse\x12)\n" +
	"\x10continue_serving\x18\x01 \x01(\bR\x0fcontinueServing\x12\x1a\n" +
	"\bcommands\x18\x02 \x03(\tR\bcommands\"g\n" +
	"\x11DeregisterRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"8\n" +
	"\x12DeregisterResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged2\xfb\x01\n" +
	"\x0fWorkerLifecycle\x12K\n" +
	"\x0eRegisterWorker\x12\x1b.codegen.v1.RegisterRequest\x1a\x1c.codegen.v1.RegisterResponse\x12H\n" +
	"\tHeartbeat\x12\x1c.codegen.v1.HeartbeatRequest\x1a\x1d.codegen.v1.HeartbeatResponse\x12Q\n" +
	"\x10DeregisterWorker\x12\x1d.codegen.v1.DeregisterRequest\x1a\x1e.codegen.v1.DeregisterResponseB9Z7github.com/altairalabs/codegen-mcp/api/proto/v1;protov1b\x06proto3"

var (
	file_api_proto_v1_worker_lifecycle_proto_rawDescOnce sync.Once
	file_api_proto_v1_worker_lifecycle_proto_rawDescData []byte
)

func file_api_proto_v1_worker_lifecycle_proto_rawDescGZIP() []byte {
	file_api_proto_v1_worker_lifecycle_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_worker_lifecycle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_worker_lifecycle_proto_rawDesc), len(file_api_proto_v1_worker_lifecycle_proto_rawDesc)))
	})
	return file_api_proto_v1_worker_lifecycle_proto_rawDescData
}

var file_api_proto_v1_worker_lifecycle_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_v1_worker_lifecycle_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_v1_worker_lifecycle_proto_goTypes = []any{
	(WorkerStatus_State)(0),    // 0: codegen.v1.WorkerStatus.State
	(*RegisterRequest)(nil),    // 1: codegen.v1.RegisterRequest
	(*WorkerCapabilities)(nil), // 2: codegen.v1.WorkerCapabilities
	(*RegisterResponse)(nil),   // 3: codegen.v1.RegisterResponse
	(*HeartbeatRequest)(nil),   // 4: codegen.v1.HeartbeatRequest
	(*SessionCapacity)(nil),    // 5: codegen.v1.SessionCapacity
	(*WorkerStatus)(nil),       // 6: codegen.v1.WorkerStatus
	(*HeartbeatResponse)(nil),  // 7: codegen.v1.HeartbeatResponse
	(*DeregisterRequest)(nil),  // 8: codegen.v1.DeregisterRequest
	(*DeregisterResponse)(nil), // 9: codegen.v1.DeregisterResponse
	nil,                        // 10: codegen.v1.WorkerCapabilities.MetadataEntry
	(*ResourceLimits)(nil),     // 11: codegen.v1.ResourceLimits
	(*SessionInfo)(nil),        // 12: codegen.v1.SessionInfo
	(*ResourceUsage)(nil),      // 13: codegen.v1.ResourceUsage
}
var file_api_proto_v1_worker_lifecycle_proto_depIdxs = []int32{
	2,  // 0: codegen.v1.RegisterRequest.capabilities:type_name -> codegen.v1.WorkerCapabilities
	11, // 1: codegen.v1.RegisterRequest.limits:type_name -> codegen.v1.ResourceLimits
	10, // 2: codegen.v1.WorkerCapabilities.metadata:type_name -> codegen.v1.WorkerCapabilities.MetadataEntry
	6,  // 3: codegen.v1.HeartbeatRequest.status:type_name -> codegen.v1.WorkerStatus
	5,  // 4: codegen.v1.HeartbeatRequest.capacity:type_name -> codegen.v1.SessionCapacity
	12, // 5: codegen.v1.SessionCapacity.sessions:type_name -> codegen.v1.SessionInfo
	0,  // 6: codegen.v1.WorkerStatus.state:type_name -> codegen.v1.WorkerStatus.State
	13, // 7: codegen.v1.WorkerStatus.current_usage:type_name -> codegen.v1.ResourceUsage
	1,  // 8: codegen.v1.WorkerLifecycle.RegisterWorker:input_type -> codegen.v1.RegisterRequest
	4,  // 9: codegen.v1.WorkerLifecycle.Heartbeat:input_type -> codegen.v1.HeartbeatRequest
	8,  // 10: codegen.v1.WorkerLifecycle.DeregisterWorker:input_type -> codegen.v1.DeregisterRequest
	3,  // 11: codegen.v1.WorkerLifecycle.RegisterWorker:output_type -> codegen.v1.RegisterResponse
	7,  // 12: codegen.v1.WorkerLifecycle.Heartbeat:output_type -> codegen.v1.HeartbeatResponse
	9,  // 13: codegen.v1.WorkerLifecycle.DeregisterWorker:output_type -> codegen.v1.DeregisterResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_v1_worker_lifecycle_proto_init() }
func file_api_proto_v1_worker_lifecycle_proto_init() {
	if File_api_proto_v1_worker_lifecycle_proto != nil {
		return
	}
	file_api_proto_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_worker_lifecycle_proto_rawDesc), len(file_api_proto_v1_worker_lifecycle_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_worker_lifecycle_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_worker_lifecycle_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_worker_lifecycle_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_worker_lifecycle_proto_msgTypes,
	}.Build()
	File_api_proto_v1_worker_lifecycle_proto = out.File
	file_api_proto_v1_worker_lifecycle_proto_goTypes = nil
	file_api_proto_v1_worker_lifecycle_proto_depIdxs = nil
}
