// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: api/proto/v1/worker_lifecycle.proto

package protov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerLifecycle_RegisterWorker_FullMethodName   = "/codegen.v1.WorkerLifecycle/RegisterWorker"
	WorkerLifecycle_Heartbeat_FullMethodName        = "/codegen.v1.WorkerLifecycle/Heartbeat"
	WorkerLifecycle_DeregisterWorker_FullMethodName = "/codegen.v1.WorkerLifecycle/DeregisterWorker"
)

// WorkerLifecycleClient is the client API for WorkerLifecycle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkerLifecycle manages worker registration and health
type WorkerLifecycleClient interface {
	// Worker registers with coordinator on startup
	RegisterWorker(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Worker sends periodic heartbeat with health status and session capacity
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Worker gracefully deregisters before shutdown
	DeregisterWorker(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*DeregisterResponse, error)
}

type workerLifecycleClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerLifecycleClient(cc grpc.ClientConnInterface) WorkerLifecycleClient {
	return &workerLifecycleClient{cc}
}

func (c *workerLifecycleClient) RegisterWorker(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, WorkerLifecycle_RegisterWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerLifecycleClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, WorkerLifecycle_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerLifecycleClient) DeregisterWorker(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*DeregisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeregisterResponse)
	err := c.cc.Invoke(ctx, WorkerLifecycle_DeregisterWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerLifecycleServer is the server API for WorkerLifecycle service.
// All implementations must embed UnimplementedWorkerLifecycleServer
// for forward compatibility.
//
// WorkerLifecycle manages worker registration and health
type WorkerLifecycleServer interface {
	// Worker registers with coordinator on startup
	RegisterWorker(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Worker sends periodic heartbeat with health status and session capacity
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Worker gracefully deregisters before shutdown
	DeregisterWorker(context.Context, *DeregisterRequest) (*DeregisterResponse, error)
	mustEmbedUnimplementedWorkerLifecycleServer()
}

// UnimplementedWorkerLifecycleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerLifecycleServer struct{}

func (UnimplementedWorkerLifecycleServer) RegisterWorker(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterWorker not implemented")
}
func (UnimplementedWorkerLifecycleServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedWorkerLifecycleServer) DeregisterWorker(context.Context, *DeregisterRequest) (*DeregisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeregisterWorker not implemented")
}
func (UnimplementedWorkerLifecycleServer) mustEmbedUnimplementedWorkerLifecycleServer() {}
func (UnimplementedWorkerLifecycleServer) testEmbeddedByValue()                         {}

// UnsafeWorkerLifecycleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerLifecycleServer will
// result in compilation errors.
type UnsafeWorkerLifecycleServer interface {
	mustEmbedUnimplementedWorkerLifecycleServer()
}

func RegisterWorkerLifecycleServer(s grpc.ServiceRegistrar, srv WorkerLifecycleServer) {
	// If the following call pancis, it indicates UnimplementedWorkerLifecycleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerLifecycle_ServiceDesc, srv)
}

func _WorkerLifecycle_RegisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerLifecycleServer).RegisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerLifecycle_RegisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerLifecycleServer).RegisterWorker(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerLifecycle_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerLifecycleServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerLifecycle_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerLifecycleServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerLifecycle_DeregisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerLifecycleServer).DeregisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerLifecycle_DeregisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerLifecycleServer).DeregisterWorker(ctx, req.(*DeregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerLifecycle_ServiceDesc is the grpc.ServiceDesc for WorkerLifecycle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerLifecycle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "codegen.v1.WorkerLifecycle",
	HandlerType: (*WorkerLifecycleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWorker",
			Handler:    _WorkerLifecycle_RegisterWorker_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _WorkerLifecycle_Heartbeat_Handler,
		},
		{
			MethodName: "DeregisterWorker",
			Handler:    _WorkerLifecycle_DeregisterWorker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/worker_lifecycle.proto",
}
